library("tidyverse")
library("dplyr")
library("sf")
library("rgdal")
library("units")
library("lwgeom")
library("raster")

setwd("/data/zool-zost/sjoh4959/projects/newproject/data")

land <- sf::st_read(dsn = "/data/zool-zost/sjoh4959/projects/newproject/data/everythingisanisland.shp") %>%
  mutate(area=st_area(.)/1000000) %>% drop_units() %>% filter(area < 587000)

resident <-
  sf::st_read(dsn = file.path(data_path("shapefiles/All_Species_Resident.shp")))

bio <- getData("worldclim", var = "bio", res = 2.5, path = file.path(data_path,"biovariables"))
alt <- getData("worldclim", var = "alt", res = 2.5, path = file.path(data_path,"biovariables"))

calculateIntersect <- function(dataset, land) {
  out <- list()
  for (i in dataset$SCINAME) {
    out[[i]] <- dataset %>% filter(SCINAME==i) %>%
      st_buffer(dist = 0.0001, nQuadSegs = 1) %>%
      st_intersection(land, proj4string = "+init=epsg:4326") %>%
      st_cast("MULTIPOLYGON") %>%
      st_cast("POLYGON")
  }
  out
}


list_outliers <- c(
  "Acanthis flammea",
  "Accipiter badius",
  "Accipiter striatus",
  "Acrocephalus palustris",
  "Aechmophorus occidentalis",
  "Anas platyrhynchos",
  "Anthus richardi",
  "Anthus rubescens",
  "Apus pacificus",
  "Apus pallidus",
  "Aquila nipalensis",
  "Ardea cinerea",
  "Ardea purpurea",
  "Arenaria interpres",
  "Calidris alpina",
  "Calidris falcinellus",
  "Caprimulgus aegyptius",
  "Cercotrichas galactotes",
  "Charadrius alexandrinus",
  "Charadrius dubius",
  "Charadrius hiaticula",
  "Charadrius leschenaultii",
  "Circus aeruginosus",
  "Coracias garrulus",
  "Cuculus canorus",
  "Cursorius cursor",
  "Elaenia albiceps",
  "Emberiza pallasi",
  "Emberiza schoeniclus",
  "Empidonax difficilis",
  "Eremophila alpestris",
  "Falco peregrinus",
  "Fringilla coelebs",
  "Fulica atra",
  "Gallinago gallinago",
  "Gallinula chloropus",
  "Gelochelidon nilotica",
  "Gymnoris xanthocollis",
  "Haematopus ostralegus",
  "Hirundapus caudacutus",
  "Hirundo rustica",
  "Horornis canturians",
  "Iduna pallida",
  "Lanius excubitor",
  "Laterallus jamaicensis",
  "Lullula arborea",
  "Merops persicus",
  "Milvus migrans",
  "Motacilla alba",
  "Motacilla citreola",
  "Motacilla tschutschensis",
  "Muscicapa dauurica",
  "Muscicapa sibirica",
  "Muscicapa striata",
  "Neophron percnopterus",
  "Onychoprion anaethetus",
  "Otus scops",
  "Passer hispaniolensis",
  "Pelecanoides georgicus",
  "Petrochelidon fulva",
  "Phalacrocorax carbo",
  "Phoenicurus ochruros",
  "Phylloscopus collybita",
  "Phylloscopus ibericus",
  "Platalea leucorodia",
  "Podiceps cristatus",
  "Puffinus persicus",
  "Pyrocephalus rubinus",
  "Rallus aquaticus",
  "Rallus limicola",
  "Remiz pendulinus",
  "Riparia riparia",
  "Sayornis saya",
  "Sterna hirundo",
  "Sterna vittata",
  "Sternula albifrons",
  "Streptopelia turtur",
  "Sturnella magna",
  "Sturnus vulgaris",
  "Sylvia communis",
  "Sylvia conspicillata",
  "Sylvia crassirostris",
  "Sylvia curruca",
  "Sylvia hortensis",
  "Tachybaptus ruficollis",
  "Upupa epops",
  "Zapornia pusilla",
  "Zoothera aurea",
  "Zosterops japonicus",
  "Fulica americana",
  "Charadrius vociferus",
  "Charadrius wilsonia",
  "Chlidonias hybrida",
  "Chloephaga picta",
  "Chordeiles acutipennis",
  "Chordeiles gundlachii",
  "Chordeiles minor",
  "Circaetus gallicus",
  "Ciconia ciconia",
  "Clamator jacobinus",
  "Petroica boodang",
  "Colaptes auratus",
  "Columba oenas",
  "Coturnix delegorguei",
  "Cuculus micropterus",
  "Egretta thula",
  "Elanoides forficatus",
  "Falco cherrug",
  "Eudyptula minor",
  "Eudynamys scolopaceus",
  "Falco columbarius",
  "Eurystomus orientalis",
  "Falco sparverius",
  "Falco subbuteo",
  "Falco tinnunculus",
  "Fregetta grallaria",
  "Fregetta tropica",
  "Gallinago solitaria",
  "Gallinula galeata",
  "Gallus gallus",
  "Gavia arctica",
  "Glareola pratincola",
  "Gygis alba",
  "Halcyon coromanda",
  "Halcyon leucocephala",
  "Hirundapus cochinchinensis",
  "Ixobrychus exilis",
  "Ixobrychus flavicollis",
  "Lagopus lagopus",
  "Arundinax aedon",
  "Anthus hodgsoni",
  "Spinus pinus",
  "Spinus tristis",
  "Thinocorus orbignyianus",
  "Zapornia fusca",
  "Corvus corax",
  "Setophaga nigrescens",
  "Emberiza citrinella",
  "Emberiza fucata",
  "Eophona migratoria",
  "Larus argentatus",
  "Limosa lapponica",
  "Oceanites oceanicus",
  "Limosa fedoa",
  "Larvivora cyane",
  "Passer cinnamomeus",
  "Sporophila nigricollis",
  "Sturnia malabarica",
  "Megaceryle torquata",
  "Metriopelia melanoptera",
  "Micrathene whitneyi",
  "Nettapus coromandelianus",
  "Ninox japonica",
  "Numenius arquata",
  "Otus sunia",
  "Pelecanoides urinatrix",
  "Pachyptila crassirostris",
  "Pachyptila desolata",
  "Patagioenas fasciata",
  "Pelagodroma marina",
  "Pernis ptilorhynchus",
  "Pluvialis apricaria",
  "Podilymbus podiceps",
  "Anous ceruleus",
  "Pseudobulweria rostrata",
  "Pterodroma neglecta",
  "Puffinus bailloni",
  "Ptychoramphus aleuticus",
  "Rallus crepitans",
  "Spatula cyanoptera",
  "Spatula versicolor",
  "Stercorarius longicaudus",
  "Sterna sumatrana",
  "Sternula nereis",
  "Sternula antillarum",
  "Streptopelia orientalis",
  "Sula nebouxii",
  "Surniculus dicruroides",
  "Systellura longirostris",
  "Tachybaptus dominicus",
  "Tanysiptera sylvia",
  "Treron sieboldii",
  "Setophaga petechia",
  "Tringa totanus",
  "Turnix tanki",
  "Zapornia akool",
  "Dicrurus hottentottus",
  "Emberiza spodocephala",
  "Hypsipetes leucocephalus",
  "Phylloscopus reguloides",
  "Luscinia megarhynchos",
  "Myiarchus tyrannulus",
  "Myiodynastes maculatus",
  "Progne subis",
  "Phylloscopus goodsoni",
  "Progne chalybea",
  "Passerculus sandwichensis",
  "Passerella iliaca",
  "Pipilo erythrophthalmus",
  "Phylloscopus trochiloides",
  "Riparia diluta",
  "Regulus ignicapilla",
  "Stelgidopteryx serripennis",
  "Sylvia mystacea",
  "Troglodytes pacificus",
  "Turdus merula",
  "Turdus migratorius",
  "Phaethon aethereus",
  "Geokichla citrina",
  "Molothrus aeneus",
  "Podiceps grisegena",
  "Pterodroma mollis",
  "Puffinus lherminieri",
  "Pygoscelis papua",
  "Uria aalge",
  "Eudynamys orientalis",
  "Locustella davidi",
  "Setophaga pinus",
  "Geokichla sibirica",
  "Pagodroma nivea",
  "Scythrops novaehollandiae",
  "Junco hyemalis",
  "Phylloscopus fuscatus",
  "Pitta sordida",
  "Sylvia atricapilla",
  "Troglodytes hiemalis",
  "Emberiza cioides",
  "Emberiza rustica",
  "Phaethon rubricauda",
  "Sula dactylatra",
  "Cistothorus palustris",
  "Anthus correndera",
  "Dicrurus leucophaeus",
  "Dicrurus macrocercus",
  "Bombycilla garrulus",
  "Catharus guttatus",
  "Catharus minimus",
  "Contopus sordidulus",
  "Coracina novaehollandiae",
  "Delichon dasypus",
  "Empidonax traillii",
  "Geothlypis trichas",
  "Icterus cucullatus",
  "Lanius ludovicianus",
  "Lanius cristatus",
  "Lanius schach",
  "Legatus leucophaius",
  "Locustella certhiola",
  "Locustella luscinioides",
  "Locustella ochotensis",
  "Melospiza lincolnii",
  "Melospiza melodia",
  "Monticola solitarius",
  "Muscisaxicola flavinucha",
  "Myiarchus cinerascens",
  "Myiagra rubecula",
  "Haematopus palliatus",
  "Haliaeetus leucocephalus",
  "Oriolus chinensis",
  "Accipiter gularis",
  "Jynx torquilla",
  "Passerina ciris",
  "Petrochelidon pyrrhonota",
  "Pheucticus melanocephalus",
  "Phoenicurus auroreus",
  "Phylloscopus trochilus",
  "Lalage melaschistos",
  "Setophaga discolor",
  "Piranga rubra",
  "Plectrophenax nivalis",
  "Polioptila caerulea",
  "Pooecetes gramineus",
  "Prunella montanella",
  "Prunella rubida",
  "Larus hyperboreus",
  "Quiscalus quiscula",
  "Regulus calendula",
  "Caprimulgus europaeus",
  "Saxicola torquatus",
  "Sialia mexicana",
  "Spizella pusilla",
  "Sylvia nisoria",
  "Sylvia borin",
  "Terpsiphone atrocaudata",
  "Oreopholus ruficollis",
  "Phalacrocorax punctatus",
  "Toxostoma rufum",
  "Turdus chrysolaus",
  "Ardea herodias",
  "Turdus viscivorus",
  "Tyrannus dominicensis",
  "Vireo bellii",
  "Vireo flavoviridis",
  "Vireo solitarius",
  "Synthliboramphus antiquus",
  "Xolmis pyrope",
  "Ixoreus naevius",
  "Accipiter nisus",
  "Alcedo atthis",
  "Anhinga anhinga",
  "Anser albifrons",
  "Charadrius mongolus",
  "Anous minutus",
  "Anser fabalis",
  "Antigone canadensis",
  "Apus apus",
  "Apus berliozi",
  "Apus affinis",
  "Aquila chrysaetos",
  "Asio flammeus",
  "Aviceda leuphotes",
  "Aythya marila",
  "Botaurus stellaris",
  "Bucephala clangula",
  "Buteo brachyurus",
  "Buteo platypterus",
  "Buteo buteo",
  "Buteo jamaicensis",
  "Buteo japonicus",
  "Buteo lagopus",
  "Buteo lineatus",
  "Butorides striata",
  "Cacomantis merulinus",
  "Calidris canutus",
  "Caprimulgus jotaka",
  "Cepphus grylle",
  "Cepphus columba",
  "Chaetura vauxi",
  "Cyanoptila cyanomelana",
  "Acrocephalus arundinaceus",
  "Acrocephalus concinens",
  "Calcarius lapponicus",
  "Linaria flavirostris",
  "Carpodacus erythrinus",
  "Cettia cetti",
  "Horornis diphone",
  "Cisticola juncidis",
  "Coccothraustes coccothraustes",
  "Motacilla cinerea",
  "Emberiza leucocephalos",
  "Emberiza aureola",
  "Cecropis daurica",
  "Larvivora akahige",
  "Larvivora komadori",
  "Locustella pryeri",
  "Monarcha frater",
  "Passer montanus",
  "Fratercula arctica",
  "Fregata minor",
  "Fulmarus glacialis",
  "Onychoprion fuscatus",
  "Fregata ariel",
  "Troglodytes aedon",
  "Sterna dougallii",
  "Xema sabini",
  "Lalage melanoptera",
  "Edolisoma tenuirostre",
  "Delichon urbicum",
  "Lanius borealis",
  "Corvus frugilegus",
  "Locustella naevia",
  "Pitta versicolor",
  "Tachycineta thalassina",
  "Vireo griseus",
  "Vireo altiloquus",
  "Vireo gilvus",
  "Lanius bucephalus",
  "Petrochelidon nigricans",
  "Ammospiza caudacuta",
  "Anthus campestris",
  "Calandrella brachydactyla",
  "Burhinus oedicnemus",
  "Caprimulgus ruficollis",
  "Anthus trivialis",
  "Anthus gustavi",
  "Anthus pratensis",
  "Catharus ustulatus",
  "Alca torda",
  "Alle alle",
  "Acrocephalus melanopogon",
  "Alauda arvensis",
  "Ammospiza maritima",
  "Ammospiza nelsoni",
  "Ammodramus savannarum",
  "Setophaga caerulescens",
  "Carpodacus sibiricus",
  "Setophaga dominica",
  "Carduelis carduelis",
  "Pycnonotus sinensis",
  "Sylvia melanocephala",
  "Troglodytes troglodytes",
  "Setophaga pitiayumi",
  "Myadestes townsendi",
  "Chloris sinica",
  "Ficedula hypoleuca",
  "Agelaius phoeniceus",
  "Anthus petrosus",
  "Carpodacus roseus",
  "Catharus fuscescens",
  "Cyanerpes cyaneus",
  "Emberiza elegans",
  "Eophona personata",
  "Leucosticte tephrocotis",
  "Melospiza georgiana",
  "Molothrus ater",
  "Pyrrhula pyrrhula",
  "Regulus satrapa",
  "Regulus regulus",
  "Seiurus aurocapilla",
  "Sialia sialis",
  "Spizella passerina",
  "Volatinia jacarina",
  "Hypsipetes amaurotis",
  "Oenanthe oenanthe",
  "Phylloscopus ogilviegranti",
  "Emberiza yessoensis",
  "Passerina caerulea",
  "Anser caerulescens",
  "Asio otus",
  "Branta canadensis",
  "Cathartes aura",
  "Chloris chloris",
  "Columba palumbus",
  "Corvus brachyrhynchos",
  "Corvus monedula",
  "Erithacus rubecula",
  "Euphagus carolinus",
  "Linaria cannabina",
  "Mergus merganser",
  "Nyctanassa violacea",
  "Podiceps auritus",
  "Podiceps nigricollis",
  "Prunella modularis",
  "Pterocles orientalis",
  "Streptopelia roseogrisea",
  "Sturnella neglecta",
  "Turdus philomelos",
  "Uria lomvia",
  "Acrocephalus aequinoctialis",
  "Acrocephalus stentoreus",
  "Alaudala rufescens",
  "Alectoris chukar",
  "Amazona aestiva",
  "Ammomanes cinctura",
  "Anthus similis",
  "Aquila fasciata",
  "Athene noctua",
  "Bubo africanus",
  "Bucanetes githagineus",
  "Celeus undatus",
  "Cinnyris asiaticus",
  "Columba livia",
  "Cypsiurus parvus",
  "Eclectus roratus",
  "Elanus caeruleus",
  "Galerida cristata",
  "Geophaps plumifera",
  "Macropygia macassariensis",
  "Malurus assimilis",
  "Megascops asio",
  "Nothura maculosa",
  "Oenanthe finschii",
  "Oenanthe lugens",
  "Oena capensis",
  "Passer domesticus",
  "Poecile montanus",
  "Prinia gracilis",
  "Psittacula eques",
  "Ptilinopus richardsii",
  "Pycnonotus simplex",
  "Saltator striatipectus",
  "Sporophila maximiliani",
  "Sterna striata",
  "Terpsiphone paradisi",
  "Tichodroma muraria",
  "Todiramphus chloris",
  "Todiramphus tutus",
  "Tyto alba",
  "Vireo chivi",
  "Zosterops auriventer",
  "Zosterops everetti",
  "Zosterops melanurus",
  "Zosterops palpebrosus",
  "Zosterops simplex",
  "Zosterops citrinella",
  "Porphyriops melanops",
  "Rubigula flaviventris",
  "Chalcophaps indica",
  "Chalcophaps longirostris",
  "Chalcopsitta atra",
  "Chalcopsitta scintillata",
  "Charadrius bicinctus",
  "Chrysocolaptes lucidus",
  "Chrysocolaptes strictus",
  "Chlorostilbon gibsoni",
  "Chlorostilbon lucidus",
  "Charmosyna placentis",
  "Charmosyna rubronotata",
  "Chelidoptera tenebrosa",
  "Chloephaga hybrida",
  "Chloroceryle aenea",
  "Chlorostilbon mellisugus",
  "Chrysophlegma flavinucha",
  "Chrysophlegma miniaceum",
  "Chrysuronia oenone",
  "Chordeiles nacunda",
  "Ciccaba huhula",
  "Ciccaba virgata",
  "Ciconia episcopus",
  "Pericrocotus cinnamomeus",
  "Coccyzus longirostris",
  "Pericrocotus solaris",
  "Perisoreus infaustus",
  "Coenocorypha aucklandica",
  "Petroica australis",
  "Colaptes chrysoides",
  "Colaptes melanochloros",
  "Colaptes punctigula",
  "Colaptes rubiginosus",
  "Platyrinchus mystaceus",
  "Platyrinchus saturatus",
  "Colinus virginianus",
  "Colius striatus",
  "Collocalia esculenta",
  "Collocalia linchi",
  "Columba vitiensis",
  "Columba janthina",
  "Columba rupestris",
  "Columbina minuta",
  "Columbina squammata",
  "Columbina talpacoti",
  "Coracias benghalensis",
  "Coracopsis nigra",
  "Corythornis cristatus",
  "Corythornis leucogaster",
  "Coracopsis vasa",
  "Coragyps atratus",
  "Crax alector",
  "Crax rubra",
  "Dacelo leachii",
  "Dacelo novaeguineae",
  "Crypturellus boucardi",
  "Crypturellus erythropus",
  "Dacelo tyro",
  "Dactylortyx thoracicus",
  "Crypturellus obsoletus",
  "Crypturellus undulatus",
  "Dasylophus superciliosus",
  "Dendragapus fuliginosus",
  "Dendrocopos analis",
  "Cyclopsitta diophthalma",
  "Cyclopsitta gulielmitertii",
  "Glaucidium siju",
  "Cypsiurus balasiensis",
  "Dendrocopos leucotos",
  "Dendrocopos macei",
  "Dendrocopos major",
  "Deroptyus accipitrinus",
  "Dinopium benghalense",
  "Dinopium rafflesii",
  "Dinopium shorii",
  "Dryobates minor",
  "Dryobates pubescens",
  "Dryocopus javensis",
  "Dryocopus martius",
  "Ducula carola",
  "Ducula cineracea",
  "Dryolimnas cuvieri",
  "Dryotriorchis spectabilis",
  "Ducula aenea",
  "Ducula aurorae",
  "Ducula badia",
  "Ducula bicolor",
  "Ducula mullerii",
  "Ducula oceanica",
  "Ducula pacifica",
  "Ducula pickeringii",
  "Ducula pinon",
  "Ducula pistrinaria",
  "Ducula rufigaster",
  "Egretta novaehollandiae",
  "Egretta rufescens",
  "Egretta sacra",
  "Elanus leucurus",
  "Eos squamata",
  "Eos histrio",
  "Ephippiorhynchus asiaticus",
  "Falco cenchroides",
  "Eubucco bourcierii",
  "Falco chicquera",
  "Lophornis chalybeus",
  "Nyctidromus albicollis",
  "Eulampis holosericeus",
  "Eumomota superciliosa",
  "Falco longipennis",
  "Eupetomena macroura",
  "Eupsittula nana",
  "Eurypyga helias",
  "Eurystomus glaucurus",
  "Eurystomus gularis",
  "Eutoxeres aquila",
  "Francolinus pictus",
  "Falcipennis canadensis",
  "Falco berigora",
  "Falco biarmicus",
  "Falco moluccensis",
  "Francolinus pintadeanus",
  "Falco rufigularis",
  "Florisuga mellivora",
  "Treron apicauda",
  "Galbula dea",
  "Gallicolumba crinigera",
  "Galbula ruficauda",
  "Gallicolumba luzonica",
  "Bradypterus lopezi",
  "Gallinago undulata",
  "Gallinula tenebrosa",
  "Phoeniculus purpureus",
  "Gecinulus grantia",
  "Gampsonyx swainsonii",
  "Geoffroyus geoffroyi",
  "Geopelia humeralis",
  "Geopelia placida",
  "Geophaps smithii",
  "Geranospiza caerulescens",
  "Geranoaetus albicaudatus",
  "Geranoaetus melanoleucus",
  "Glaucidium brasilianum",
  "Glaucidium brodiei",
  "Glaucidium capense",
  "Glaucidium radiatum",
  "Glaucidium passerinum",
  "Glaucis hirsutus",
  "Goura victoria",
  "Gymnocrex plumbeiventris",
  "Spinus magellanicus",
  "Psilopogon chrysopogon",
  "Guttera plumifera",
  "Guttera pucherani",
  "Gymnobucco calvus",
  "Gymnophaps albertisii",
  "Haematopus fuliginosus",
  "Halcyon albiventris",
  "Halcyon badia",
  "Halcyon chelicuti",
  "Halcyon malimbica",
  "Halcyon senegalensis",
  "Haliastur indus",
  "Harpactes erythrocephalus",
  "Harpactes fasciatus",
  "Harpactes kasumba",
  "Harpactes oreskios",
  "Harpactes orrhophaeus",
  "Harpactes ardens",
  "Harpactes diardii",
  "Pionus maximiliani",
  "Pionus menstruus",
  "Harpagus bidentatus",
  "Hemiprocne comata",
  "Hemiprocne longipennis",
  "Heliomaster constantii",
  "Hemiprocne mystacea",
  "Henicophaps albifrons",
  "Heliomaster longirostris",
  "Herpetotheres cachinnans",
  "Heliothryx auritus",
  "Hirundapus giganteus",
  "Horizocerus albocristatus",
  "Hydropsalis cayennensis",
  "Hydropsalis climacocerca",
  "Hydropsalis torquata",
  "Pygiptila stellaris",
  "Hylocharis cyanus",
  "Hylocharis eliciae",
  "Indicator exilis",
  "Indicator maculatus",
  "Indicator minor",
  "Pyriglena leuconota",
  "Jacamerops aureus",
  "Jacana jacana",
  "Jacana spinosa",
  "Juliamyia julie",
  "Lacedo pulchella",
  "Acanthiza apicalis",
  "Acanthiza lineata",
  "Polihierax insignis",
  "Acrocephalus gracilirostris",
  "Aethopyga saturata",
  "Sittasomus griseicapillus",
  "Aegithina lafresnayei",
  "Aegithina tiphia",
  "Aethopyga boltoni",
  "Aethopyga primigenia",
  "Ailuroedus melanotis",
  "Amblycercus holosericeus",
  "Stelgidillas gracilirostris",
  "Arizelocichla tephrolaema",
  "Anthochaera carunculata",
  "Anthochaera paradoxa",
  "Hedydipna collaris",
  "Polyboroides typus",
  "Anthreptes reichenowi",
  "Chalcoparia singalensis",
  "Anthus berthelotii",
  "Anthus rufulus",
  "Aplonis zelandica",
  "Aplonis magna",
  "Aplonis panayensis",
  "Arremon aurantiirostris",
  "Arremon schlegeli",
  "Asthenes modesta",
  "Todiramphus australasia",
  "Brachypteryx leucophris",
  "Bernieria madagascariensis",
  "Agricola pallidus",
  "Bias musicus",
  "Bleda syndactylus",
  "Locustella caudata",
  "Calyptomena viridis",
  "Campylorhynchus nuchalis",
  "Camptostoma obsoletum",
  "Campylorhamphus pusillus",
  "Certhia brachydactyla",
  "Cercomacroides laeta",
  "Cercomacroides tyrannina",
  "Horornis ruficapilla",
  "Thinocorus rumicivorus",
  "Chrysomma sinense",
  "Cissa hypoleuca",
  "Cisticola bulliens",
  "Colluricincla harmonica",
  "Colonia colonus",
  "Conopias albovittatus",
  "Contopus caribaeus",
  "Coracina atriceps",
  "Edolisoma ceramense",
  "Lalage fimbriata",
  "Gavicalis versicolor",
  "Vanellus tectus",
  "Coracina temminckii",
  "Pyrrhocorax graculus",
  "Corvus coronoides",
  "Pyrrhocorax pyrrhocorax",
  "Corvus woodfordi",
  "Corydon sumatranus",
  "Corythopis torquatus",
  "Cossypha heuglini",
  "Culicicapa ceylonensis",
  "Culicicapa helianthea",
  "Cyanoloxia brissonii",
  "Cyanocompsa parellina",
  "Setophaga vitellina",
  "Cyanocorax yucatanicus",
  "Cymbilaimus lineatus",
  "Cyornis banyumas",
  "Cyornis concretus",
  "Cyornis rufigastra",
  "Dacnis cayana",
  "Dicaeum aeneum",
  "Dicaeum chrysorrheum",
  "Zosterops minor",
  "Dendrocincla anabatina",
  "Dendrocitta formosae",
  "Dendrocitta vagabunda",
  "Cyanoloxia cyanoides",
  "Dicaeum igniferum",
  "Dicaeum maugei",
  "Dicaeum nigrilore",
  "Dicrurus aeneus",
  "Elaenia flavogaster",
  "Dryoscopus angolensis",
  "Enicurus maculatus",
  "Apalis rufogularis",
  "Erythrocercus mccallii",
  "Cercotrichas leucophrys",
  "Euphonia affinis",
  "Cercotrichas paena",
  "Euphonia chrysopasta",
  "Hirundo smithii",
  "Eumyias thalassinus",
  "Euphonia violacea",
  "Euplectes albonotatus",
  "Lorius garrulus",
  "Lorius hypoinochrous",
  "Lorius lory",
  "Ficedula basilanica",
  "Furnarius rufus",
  "Trochalopteron milnei",
  "Garrulax monileger",
  "Garrulax rufifrons",
  "Geositta cunicularia",
  "Gerygone dorsalis",
  "Geospiza scandens",
  "Gerygone chloronota",
  "Habia fuscicauda",
  "Nyctiphrynus ocellatus",
  "Tyto rosenbergii",
  "Hemixos castanonotus",
  "Tyto tenebricosa",
  "Ptyonoprogne concolor",
  "Pachysylvia hypoxantha",
  "Pachysylvia muscicapina",
  "Hylophylax naevioides",
  "Hypocnemis striata",
  "Ixos mcclellandii",
  "Icterus chrysater",
  "Notopholia corusca",
  "Nesoptilotis leucotis",
  "Ptilotula penicillata",
  "Ptilotula plumula",
  "Caligavis chrysops",
  "Ptilotula flavescens",
  "Stomiopera flava",
  "Ptilotula fusca",
  "Larus occidentalis",
  "Laterallus albigularis",
  "Laterallus melanophaius",
  "Phylloscopus castaniceps",
  "Leiopicus mahrattensis",
  "Lepidopyga coeruleogularis",
  "Leptodon cayanensis",
  "Leptosomus discolor",
  "Arachnothera longirostra",
  "Arachnothera modesta",
  "Leptotila rufaxilla",
  "Leptotila verreauxi",
  "Lewinia striata",
  "Lissotis melanogaster",
  "Spermestes cucullata",
  "Lophonetta specularioides",
  "Lophostrix cristata",
  "Lophotriorchis kienerii",
  "Lophura leucomelanos",
  "Lophura nycthemera",
  "Loriculus aurantiifrons",
  "Oedistoma iliolophus",
  "Lurocalis semitorquatus",
  "Mixornis gularis",
  "Macronus ptilosus",
  "Macronus striaticeps",
  "Odontophorus gujanensis",
  "Symposiachrus infelix",
  "Ficedula hodgsoni",
  "Fraseria griseigularis",
  "Myrmophylax atrothorax",
  "Bradornis comitatus",
  "Chalcomitra amethystina",
  "Isleria hauxwelli",
  "Turdinus brevicaudatus",
  "Chalcomitra adelberti",
  "Cinnyris chloropygius",
  "Cinnyris humbloti",
  "Cinnyris lotenius",
  "Cinnyris solaris",
  "Cinnyris sovimanga",
  "Chalcomitra rubescens",
  "Cyanomitra verticalis",
  "Leptocoma zeylonica",
  "Turdus eremita",
  "Todiramphus nigrocyaneus",
  "Sporophila crassirostris",
  "Psittiparus gularis",
  "Poecile carolinensis",
  "Poecile cinctus",
  "Lophophanes cristatus",
  "Poecile hudsonicus",
  "Poecile rufescens",
  "Myiothlypis fulvicauda",
  "Machlolophus spilonotus",
  "Ceratopipra erythrocephala",
  "Ceratopipra mentalis",
  "Geospizopsis unicolor",
  "Gliciphila melanops",
  "Gliciphila notabilis",
  "Pseudorectes ferrugineus",
  "Hydrornis cyaneus",
  "Hydrornis oatesi",
  "Hydrornis soror",
  "Merops superciliosus",
  "Merops variegatus",
  "Microcarbo melanoleucos",
  "Cyornis olivaceus",
  "Phoenicurus fuliginosus",
  "Crithagra burtoni",
  "Crithagra capistrata",
  "Aegithalos caudatus",
  "Cyanoderma chrysaeum",
  "Sterrhoptilus nigrocapitatus",
  "Cyanoderma ruficeps",
  "Stachyris strialata",
  "Zosterornis whiteheadi",
  "Sylvia subcoerulea",
  "Camaroptera brachyura",
  "Euchrepomis spodioptila",
  "Camaroptera chloronota",
  "Thryophilus pleurostictus",
  "Cantorchilus superciliaris",
  "Cantorchilus nigricapillus",
  "Pheugopedius rutilus",
  "Asemospiza obscura",
  "Turdinus marmoratus",
  "Urocissa erythroryncha",
  "Northiella haematogaster",
  "Notharchus hyperrhynchus",
  "Notharchus tectus",
  "Megapodius freycinet",
  "Lybius vieilloti",
  "Lyncornis macrotis",
  "Macheiramphus alcinus",
  "Macropygia amboinensis",
  "Macropygia emiliana",
  "Macropygia mackinlayi",
  "Macropygia tenuirostris",
  "Macropygia unchall",
  "Margarobyas lawrencii",
  "Megaceryle lugubris",
  "Megaceryle maxima",
  "Megapodius cumingii",
  "Megapodius laperouse",
  "Microdynamis parva",
  "Megascops nudipes",
  "Microhierax caerulescens",
  "Microhierax erythrogenys",
  "Megascops choliba",
  "Megapodius nicobariensis",
  "Megapodius reinwardt",
  "Micronisus gabar",
  "Micropsitta bruijnii",
  "Micropsitta finschii",
  "Megascops guatemalae",
  "Megascops kennicottii",
  "Micropsitta geelvinkiana",
  "Meiglyptes tukki",
  "Melanerpes aurifrons",
  "Melanerpes formicivorus",
  "Melanerpes pygmaeus",
  "Melanoperdix niger",
  "Melanerpes rubricapillus",
  "Melidora macrorrhina",
  "Mulleripicus fulvus",
  "Mellisuga minima",
  "Merganetta armata",
  "Merops bullockoides",
  "Merops orientalis",
  "Merops pusillus",
  "Neomorphus geoffroyi",
  "Micrastur ruficollis",
  "Micrastur semitorquatus",
  "Microcarbo africanus",
  "Micropsitta meeki",
  "Micropternus brachyurus",
  "Micropygia schomburgkii",
  "Milvago chimachima",
  "Momotus lessonii",
  "Momotus momota",
  "Phaethornis augusti",
  "Monasa morphoeus",
  "Monasa nigrifrons",
  "Mulleripicus funebris",
  "Mulleripicus pulverulentus",
  "Myrtis fanny",
  "Nesoctites micromegas",
  "Netta erythrophthalma",
  "Nestor meridionalis",
  "Ninox jacquinoti",
  "Ninox philippensis",
  "Ninox scutulata",
  "Polytmus theresiae",
  "Ninox spilonotus",
  "Ninox variegata",
  "Nisaetus cirrhatus",
  "Nisaetus nanus",
  "Nisaetus nipalensis",
  "Nonnula rubecula",
  "Taccocua leschenaultii",
  "Nyctibius aethereus",
  "Nyctibius jamaicensis",
  "Nycticorax caledonicus",
  "Nyctipolus hirundinaceus",
  "Nyctiprogne leucopyga",
  "Nyctyornis athertoni",
  "Nystalus chacuru",
  "Ocyphaps lophotes",
  "Oceanites gracilis",
  "Odontophorus capueira",
  "Cymbirhynchus macrorhynchos",
  "Otis tarda",
  "Otus bakkamoena",
  "Otus lempiji",
  "Otus lettia",
  "Otus magicus",
  "Otus brucei",
  "Otus mantananensis",
  "Otus spilocephalus",
  "Otus rufescens",
  "Otus semitorques",
  "Peliperdix lathami",
  "Panyptila cayennensis",
  "Pardirallus nigricans",
  "Pardirallus sanguinolentus",
  "Patagioenas cayennensis",
  "Patagioenas flavirostris",
  "Petroica pusilla",
  "Patagioenas inornata",
  "Penelope purpurascens",
  "Penelope superciliaris",
  "Penelopides affinis",
  "Patagioenas plumbea",
  "Vanellus chilensis",
  "Patagioenas subvinacea",
  "Pavo muticus",
  "Pelargopsis capensis",
  "Pelargopsis melanorhyncha",
  "Pelecanus occidentalis",
  "Penelope jacquacu",
  "Phaenicophaeus tristis",
  "Penelope marail",
  "Vanellus indicus",
  "Penelopides panini",
  "Phaethornis eurynome",
  "Perdix dauurica",
  "Perdix perdix",
  "Pernis steerei",
  "Petrophassa albipennis",
  "Phaethornis guy",
  "Phaenicophaeus curvirostris",
  "Phaenicophaeus diardi",
  "Phaethornis anthophilus",
  "Phaethornis striigularis",
  "Phaethornis longirostris",
  "Phaethornis malaris",
  "Phaethornis ruber",
  "Phaethornis superciliosus",
  "Platycercus eximius",
  "Platycercus icterotis",
  "Phaetusa simplex",
  "Phalacrocorax varius",
  "Phalaenoptilus nuttallii",
  "Phaps elegans",
  "Phasianus colchicus",
  "Petronia petronia",
  "Phacellodomus rufifrons",
  "Phodilus assimilis",
  "Phoeniculus bollei",
  "Piculus flavigula",
  "Picumnus aurifrons",
  "Picumnus cinnamomeus",
  "Picumnus cirratus",
  "Psilopogon faber",
  "Picus canus",
  "Picus chlorolophus",
  "Picus erythropygius",
  "Picus puniceus",
  "Psilopogon faiostrictus",
  "Picumnus sclateri",
  "Picus viridis",
  "Podargus ocellatus",
  "Podargus strigoides",
  "Podica senegalensis",
  "Platycercus adscitus",
  "Podiceps major",
  "Prioniturus platurus",
  "Priotelus temnurus",
  "Prodotiscus insignis",
  "Psephotus haematonotus",
  "Psilopogon duvaucelii",
  "Psilopogon lagrandieri",
  "Mionectes macconnelli",
  "Psilopogon lineatus",
  "Psilopogon mystacophanos",
  "Psilopogon armillaris",
  "Psilopogon incognitus",
  "Psilopogon haemacephalus",
  "Psilopogon henricii",
  "Psilopogon virens",
  "Psilopogon zeylanicus",
  "Psilopsiagon aurifrons",
  "Psittacara leucophthalmus",
  "Psittacula alexandri",
  "Psittacula eupatria",
  "Pteroglossus torquatus",
  "Psittaculirostris desmarestii",
  "Psittacula longicauda",
  "Psittacula roseata",
  "Psittinus cyanurus",
  "Streptoprocne rutila",
  "Pternistis squamatus",
  "Pterocles lichtensteinii",
  "Pteroglossus aracari",
  "Mionectes oleagineus",
  "Pteroglossus bitorquatus",
  "Ptilinopus dupetithouarsii",
  "Ptilinopus iozonus",
  "Ptilinopus melanospilus",
  "Ptilinopus perlatus",
  "Ptilinopus perousii",
  "Ptilinopus pulchellus",
  "Ramphastos tucanus",
  "Ramphastos vitellinus",
  "Ptilinopus purpuratus",
  "Ptilinopus rarotongensis",
  "Ptilinopus regina",
  "Ptilinopus solomonensis",
  "Ptilinopus viridis",
  "Pucrasia macrolopha",
  "Reinwardtoena reinwardti",
  "Pulsatrix perspicillata",
  "Rhamphococcyx calyorhynchus",
  "Rhea americana",
  "Rhynchortyx cinctus",
  "Rallina eurizonoides",
  "Radjah radjah",
  "Rallus longirostris",
  "Ramphastos ambiguus",
  "Ramphastos sulfuratus",
  "Ramphastos toco",
  "Rhinopomastus aterrimus",
  "Rhodopis vesper",
  "Rhynchotus rufescens",
  "Rostrhamus sociabilis",
  "Sasia abnormis",
  "Sasia ochracea",
  "Rhyticeros plicatus",
  "Rupornis magnirostris",
  "Strix aluco",
  "Sarothrura pulchra",
  "Sarothrura rufa",
  "Surniculus lugubris",
  "Scopus umbretta",
  "Surniculus velutinus",
  "Syma torotoro",
  "Synoicus chinensis",
  "Synoicus ypsilophorus",
  "Selasphorus sasin",
  "Smutsornis africanus",
  "Spilornis cheela",
  "Spizaetus ornatus",
  "Spizaetus tyrannus",
  "Streptopelia decipiens",
  "Streptopelia tranquebarica",
  "Streptoprocne zonaris",
  "Strix ocellata",
  "Strix rufipes",
  "Strix seloputo",
  "Strix uralensis",
  "Strix varia",
  "Strix woodfordii",
  "Strix leptogrammica",
  "Strix nivicolum",
  "Surnia ulula",
  "Tetrao urogalloides",
  "Tetrao urogallus",
  "Tachornis phoenicobia",
  "Tachornis squamata",
  "Tachybaptus novaehollandiae",
  "Talegalla fuscirostris",
  "Talegalla jobiensis",
  "Talegalla cuvieri",
  "Tapera naevia",
  "Tauraco persa",
  "Tanygnathus megalorynchos",
  "Tanygnathus sumatranus",
  "Telacanthura ussheri",
  "Thalasseus bengalensis",
  "Thalasseus bergii",
  "Poodytes punctatus",
  "Threnetes ruckeri",
  "Threskiornis bernieri",
  "Trogon melanocephalus",
  "Tigrisoma lineatum",
  "Trogon melanurus",
  "Tinamus tao",
  "Todiramphus macleayii",
  "Treron griseicauda",
  "Todiramphus winchelli",
  "Treron sphenurus",
  "Trogon curucui",
  "Topaza pella",
  "Treron formosae",
  "Treron fulvicollis",
  "Treron axillaris",
  "Treron bicinctus",
  "Treron calvus",
  "Treron phoenicopterus",
  "Trichoglossus capistratus",
  "Trichoglossus forsteni",
  "Trichoglossus moluccanus",
  "Tricholaema hirsuta",
  "Tricholaema leucomelas",
  "Dacnis lineata",
  "Dacnis venusta",
  "Trogon elegans",
  "Trogon massena",
  "Trogon collaris",
  "Trogon rufus",
  "Trogon viridis",
  "Trugon terrestris",
  "Turnix maculosus",
  "Turnix ocellatus",
  "Turnix suscitator",
  "Turnix sylvaticus",
  "Turnix varius",
  "Tyto longimembris",
  "Vanellus senegallus",
  "Xiphidiopicus percussus",
  "Zapornia tabuensis",
  "Zenaida auriculata",
  "Zenaida aurita",
  "Zenaida macroura",
  "Zenaida galapagoensis",
  "Zoonavena grandidieri",
  "Aethopyga christinae",
  "Acrocephalus percernis",
  "Aethopyga flagrans",
  "Aethopyga guimarasensis",
  "Aethopyga siparaja",
  "Acrocephalus mendanae",
  "Aegithalos concinnus",
  "Aegithalos glaucogularis",
  "Mirafra africana",
  "Alophoixus ochraceus",
  "Alophoixus pallidus",
  "Anthreptes malacensis",
  "Anthreptes griseigularis",
  "Anthus cinnamomeus",
  "Anthus lutescens",
  "Aphelocoma californica",
  "Automolus infuscatus",
  "Calamanthus campestris",
  "Calamonastes undosus",
  "Conopophaga lineata",
  "Contopus cinereus",
  "Edolisoma holopolium",
  "Chloropsis cochinchinensis",
  "Cisticola exilis",
  "Cistothorus platensis",
  "Coracina caledonica",
  "Cracticus argenteus",
  "Coracina welchmani",
  "Corvus macrorhynchos",
  "Cyanolanius madagascarinus",
  "Dendrocolaptes sanctithomae",
  "Cyornis sumatrensis",
  "Deconychura longicauda",
  "Deleornis fraseri",
  "Dendrocincla fuliginosa",
  "Dicaeum hirundinaceum",
  "Dicaeum ignipectus",
  "Dicaeum minullum",
  "Dicaeum sanguinolentum",
  "Dicrurus paradiseus",
  "Dicrurus adsimilis",
  "Elaenia chiriquensis",
  "Emberiza striolata",
  "Emberiza tahapisi",
  "Entomyzon cyanotis",
  "Erythropitta rubrinucha",
  "Erythropitta rufiventris",
  "Erythropitta erythrogaster",
  "Erythropitta macklotii",
  "Erythropitta novaehibernicae",
  "Furnarius leucopus",
  "Estrilda atricapilla",
  "Euscarthmus meloryphus",
  "Formicarius analis",
  "Formicivora grisea",
  "Foudia eminentissima",
  "Gerygone flavolateralis",
  "Gracupica contra",
  "Gymnopithys bicolor",
  "Graminicola striatus",
  "Hirundo tahitica",
  "Hylophilus flavipes",
  "Tunchiornis ochraceiceps",
  "Hylophilus thoracicus",
  "Hypothymis azurea",
  "Hypothymis puella",
  "Illadopsis rufipennis",
  "Irena puella",
  "Lalage leucomela",
  "Laniisoma elegans",
  "Lanius collaris",
  "Leiothrix argentauris",
  "Manacus manacus",
  "Cincloramphus macrurus",
  "Cincloramphus timoriensis",
  "Myrmoderus ferrugineus",
  "Melanocorypha calandra",
  "Monarcha castaneiventris",
  "Myiobius sulphureipygius",
  "Myiagra castaneigularis",
  "Myiarchus swainsoni",
  "Myiarchus tuberculifer",
  "Myrmoborus lugubris",
  "Myiobius barbatus",
  "Myiopagis viridicata",
  "Myiophobus fasciatus",
  "Myrmotherula schisticolor",
  "Myrmeciza longipes",
  "Myzomela cruentata",
  "Myzomela eques",
  "Napothera epilepidota",
  "Cinnyris bifasciatus",
  "Leptocoma brasiliana",
  "Oriolus cruentus",
  "Oriolus steerii",
  "Oriolus traillii",
  "Orthotomus castaneiceps",
  "Pachycephala fulvotincta",
  "Pachycephala rufiventris",
  "Pachycephala leucogastra",
  "Pachycephala orioloides",
  "Pachycephala vitiensis",
  "Pachyramphus major",
  "Pachyramphus rufus",
  "Pachyramphus viridis",
  "Panurus biarmicus",
  "Procnias averano",
  "Poecile lugubris",
  "Cyanistes teneriffae",
  "Sittiparus varius",
  "Pellorneum capistratum",
  "Percnostola rufifrons",
  "Petroica macrocephala",
  "Phaeomyias murina",
  "Pipilo maculatus",
  "Phyllomyias burmeisteri",
  "Phylloscopus canariensis",
  "Pitohui cerviniventris",
  "Ornorectes cristatus",
  "Pitohui kirhocephalus",
  "Pitohui uropygialis",
  "Poecilotriccus plumbeiceps",
  "Platylophus galericulatus",
  "Ploceus nigricollis",
  "Prinia flaviventris",
  "Pomatorhinus ruficollis",
  "Riparia paludicola",
  "Laticilla burnesii",
  "Prinia superciliaris",
  "Prionops rufiventris",
  "Pycnonotus finlaysoni",
  "Pteruthius aeralatus",
  "Ptilorrhoa caerulescens",
  "Brachypodius atriceps",
  "Thamnophilus nigrocinereus",
  "Pycnonotus bimaculatus",
  "Thamnophilus ruficapillus",
  "Thamnophilus stictocephalus",
  "Pycnonotus plumosus",
  "Ramphotrigon megacephalum",
  "Rhabdornis inornatus",
  "Rhipidura albicollis",
  "Rhipidura albiscapa",
  "Rhipidura cockerelli",
  "Rhipidura cyaniceps",
  "Rhipidura dryas",
  "Rhipidura fuliginosa",
  "Rhynchocyclus olivaceus",
  "Rhipidura javanica",
  "Rhipidura rufifrons",
  "Rhipidura rufiventris",
  "Rhipidura superciliaris",
  "Rhipidura verreauxi",
  "Sclerurus albigularis",
  "Sclerurus caudacutus",
  "Sakesphorus canadensis",
  "Saxicola dacotiae",
  "Sclerurus rufigularis",
  "Schiffornis turdina",
  "Schiffornis veraepacis",
  "Phylloscopus intensior",
  "Phylloscopus maforensis",
  "Seleucidis melanoleucus",
  "Sericornis nouhuysi",
  "Sirystes sibilator",
  "Serpophaga subcristata",
  "Serilophus lunatus",
  "Psarocolius bifasciatus",
  "Chrysocorythus estherae",
  "Sitta carolinensis",
  "Sporophila corvina",
  "Sporophila morelleti",
  "Cyanoderma erythropterum",
  "Cyanoderma rufifrons",
  "Suiriri suiriri",
  "Sylvia abyssinica",
  "Sylvia undata",
  "Synallaxis erythrothorax",
  "Synallaxis stictothorax",
  "Synallaxis scutata",
  "Tachuris rubrigastra",
  "Tesia everetti",
  "Tachycineta euchrysea",
  "Taeniotriccus andrei",
  "Telophorus viridis",
  "Tephrodornis pondicerianus",
  "Tephrodornis virgatus",
  "Terpsiphone affinis",
  "Terpsiphone cinnamomea",
  "Tolmomyias sulphurescens",
  "Tityra semifasciata",
  "Tolmomyias assimilis",
  "Tolmomyias flaviventris",
  "Turdinus crispifrons",
  "Turdinus macrodactylus",
  "Turdoides striata",
  "Turdus albicollis",
  "Turdus chiguanco",
  "Turdus obsoletus",
  "Turdus plumbeus",
  "Turdus poliocephalus",
  "Vireo crassirostris",
  "Turdus simillimus",
  "Turdus swalesi",
  "Vireolanius leucotis",
  "Xenops minutus",
  "Xiphorhynchus susurrans",
  "Zosterops meyeni",
  "Basileuterus culicivorus",
  "Cacicus cela",
  "Certhidea fusca",
  "Geothlypis aequinoctialis",
  "Gracula religiosa",
  "Pipraeidea bonariensis",
  "Saltator coerulescens",
  "Picumnus spilogaster",
  "Ploceus ocularis",
  "Rhytipterna simplex",
  "Rhipidura diluta",
  "Sayornis nigricans",
  "Abroscopus albogularis",
  "Apus nipalensis",
  "Accipiter toussenelii",
  "Philentoma pyrhoptera",
  "Philentoma velata",
  "Pogoniulus subsulphureus",
  "Accipiter bicolor",
  "Accipiter cirrocephalus",
  "Corythornis vintsioides",
  "Aepypodius arfakianus",
  "Enicognathus ferrugineus",
  "Gallicolumba rufigula",
  "Geotrygon violacea",
  "Glaucidium cuculoides",
  "Aethopyga gouldiae",
  "Cacicus haemorrhous",
  "Cardinalis sinuatus",
  "Cinclodes patagonicus",
  "Caryothraustes poliogaster",
  "Cataponera turdoides",
  "Chamaea fasciata",
  "Edolisoma morio",
  "Lalage polioptera",
  "Corcorax melanorhamphos",
  "Corvus tasmanicus",
  "Cranioleuca subcristata",
  "Dicaeum annae",
  "Dicaeum pectorale",
  "Ficedula westermanni",
  "Formicarius nigricapillus",
  "Anthipes solitaris",
  "Gnorimopsar chopi",
  "Pachysylvia aurantiifrons",
  "Pachysylvia decurtata",
  "Schistolais leucopogon",
  "Hypocnemoides melanopogon",
  "Lewinia pectoralis",
  "Lophura ignita",
  "Loriculus philippensis",
  "Symposiachrus browni",
  "Carterornis pileatus",
  "Fraseria caerulescens",
  "Myrmecocichla monticola",
  "Nesillas typica",
  "Oriolus brachyrynchus",
  "Macropygia ruficeps",
  "Mearnsia novaeguineae",
  "Micropsitta keiensis",
  "Micropsitta pusio",
  "Ninox connivens",
  "Ninox novaeseelandiae",
  "Ninox rufa",
  "Ninox theomacha",
  "Nyctibius griseus",
  "Cyanopica cyanus",
  "Odontophorus erythrops",
  "Pardirallus maculatus",
  "Picoides tridactylus",
  "Picumnus innominatus",
  "Pionites melanocephalus",
  "Polytmus guainumbi",
  "Poicephalus cryptoxanthus",
  "Poicephalus gulielmi",
  "Polyplectron bicalcaratum",
  "Polyplectron chalcurum",
  "Probosciger aterrimus",
  "Ptilinopus cinctus",
  "Ptilinopus coronulatus",
  "Rollandia rolland",
  "Sarothrura elegans",
  "Schoutedenapus myoptilus",
  "Spilornis rufipectus",
  "Syrmaticus soemmerringii",
  "Tanysiptera galatea",
  "Tanysiptera nigriceps",
  "Theristicus caudatus",
  "Threnetes leucurus",
  "Tinamus major",
  "Touit purpuratus",
  "Turtur brehmeri",
  "Tympanuchus phasianellus",
  "Urocolius indicus",
  "Zenaida asiatica",
  "Alophoixus bres",
  "Apalis flavida",
  "Arremon taciturnus",
  "Ploceus hypoxanthus",
  "Gymnopithys rufigula",
  "Coracina striata",
  "Euplectes ardens",
  "Eurylaimus javanicus",
  "Gerygone magnirostris",
  "Hypsipetes everetti",
  "Lichmera indistincta",
  "Lycocorax pyrrhopterus",
  "Machaeropterus pyrocephalus",
  "Malacopteron magnirostre",
  "Malurus alboscapulatus",
  "Mirafra javanica",
  "Xiphorhynchus flavigaster",
  "Myiopagis caniceps",
  "Myiopagis gaimardii",
  "Myrmotherula axillaris",
  "Nucifraga caryocatactes",
  "Onychorhynchus coronatus",
  "Philemon buceroides",
  "Philemon citreogularis",
  "Anabacerthia ruficaudata",
  "Phleocryptes melanops",
  "Pica pica",
  "Ploceus manyar",
  "Poecilotriccus fumifrons",
  "Polioptila plumbea",
  "Polystictus pectoralis",
  "Pyrrhula nipalensis",
  "Riparia chinensis",
  "Sericornis beccarii",
  "Thamnophilus aethiops",
  "Thamnophilus atrinucha",
  "Torreornis inexpectata",
  "Toxorhamphus novaeguineae",
  "Tregellasia leucops",
  "Turdus assimilis",
  "Xiphorhynchus guttatus",
  "Zosterops abyssinicus",
  "Agelaioides badius",
  "Agelaius xanthomus",
  "Myiothlypis rivularis",
  "Piranga flava",
  "Tangara mexicana",
  "Tangara velia",
  "Abroscopus superciliaris",
  "Acanthiza ewingii",
  "Acanthiza nana",
  "Acanthiza pusilla",
  "Agriornis montanus",
  "Acanthorhynchus tenuirostris",
  "Agriornis lividus",
  "Acridotheres cristatellus",
  "Acridotheres fuscus",
  "Acrocephalus atyphus",
  "Acrocephalus kerearako",
  "Aegithina viridissima",
  "Agelaius assimilis",
  "Amandava amandava",
  "Alauda gulgula",
  "Alophoixus phaeocephalus",
  "Clytorhynchus pachycephaloides",
  "Ammodramus aurifrons",
  "Anairetes parulus",
  "Anairetes reguloides",
  "Dendrocincla merula",
  "Arachnothera chrysogenys",
  "Apalopteron familiare",
  "Arachnothera magna",
  "Arachnothera robusta",
  "Aplonis opaca",
  "Asthenes baeri",
  "Artamus cyanopterus",
  "Attila bolivianus",
  "Automolus leucophthalmus",
  "Smicrornis brevirostris",
  "Calamanthus fuliginosus",
  "Tarsiger indicus",
  "Cisticola erythrops",
  "Campylorhamphus trochilirostris",
  "Campylorhynchus brunneicapillus",
  "Terenotriccus erythrurus",
  "Cryptospiza reichenovii",
  "Cyornis caerulatus",
  "Catherpes mexicanus",
  "Cercomacra cinerascens",
  "Tyrannus caudifasciatus",
  "Cyornis hyacinthinus",
  "Certhiaxis cinnamomeus",
  "Certhia americana",
  "Chlamydera nuchalis",
  "Chlorocichla falkensteini",
  "Chlorophanes spiza",
  "Chloropsis aurifrons",
  "Chloropsis cyanopogon",
  "Chloropsis sonnerati",
  "Chondestes grammacus",
  "Cinclocerthia gutturalis",
  "Cinclodes oustaleti",
  "Cinclosoma ajax",
  "Accipiter tachiro",
  "Cinclus mexicanus",
  "Cinclus pallasii",
  "Cissa chinensis",
  "Cisticola lateralis",
  "Climacteris picumnus",
  "Myadestes elisabeth",
  "Cnipodectes subbrunneus",
  "Coereba flaveola",
  "Myadestes genibarbis",
  "Accipiter trivirgatus",
  "Conopophaga melanops",
  "Accipiter virgatus",
  "Contopus hispaniolensis",
  "Coracina boyeri",
  "Coracina larvata",
  "Coracina personata",
  "Cormobates leucophaea",
  "Corvus fuscicapillus",
  "Cossypha niveicapilla",
  "Cracticus mentalis",
  "Cracticus nigrogularis",
  "Curaeus curaeus",
  "Cyclarhis gujanensis",
  "Cyanerpes caeruleus",
  "Cyanocitta cristata",
  "Dendrocolaptes certhia",
  "Dicaeum bicolor",
  "Dicaeum cruentatum",
  "Dicaeum erythrorhynchos",
  "Dicaeum hypoleucum",
  "Dicaeum nitidum",
  "Dicaeum pygmaeum",
  "Dicaeum trigonostigma",
  "Dicaeum trochileum",
  "Dicrurus andamanensis",
  "Dicrurus balicassius",
  "Dicrurus caerulescens",
  "Dryoscopus cubla",
  "Dryoscopus gambensis",
  "Elaenia cristata",
  "Inezia subflava",
  "Elminia nigromitrata",
  "Iodopleura isabellae",
  "Enicurus leschenaulti",
  "Epthianura crocea",
  "Eremomela scotops",
  "Enicurus velatus",
  "Eopsaltria australis",
  "Eopsaltria griseogularis",
  "Eremopterix verticalis",
  "Erpornis zantholeuca",
  "Erythrura prasina",
  "Estrilda nonnula",
  "Estrilda perreini",
  "Eupetes macrocerus",
  "Euphonia fulvicrissa",
  "Euphonia gouldi",
  "Euplectes capensis",
  "Euplectes macroura",
  "Aquila rapax",
  "Ficedula buruensis",
  "Geothlypis poliocephala",
  "Geothlypis rostrata",
  "Ficedula tricolor",
  "Formicarius colma",
  "Formicivora melanogaster",
  "Fraseria ocreata",
  "Gerygone levigaster",
  "Garrulax leucolophus",
  "Gerygone fusca",
  "Gerygone olivacea",
  "Gerygone palpebrosa",
  "Gerygone tenebrosa",
  "Granatellus sallaei",
  "Gymnocichla nudiceps",
  "Hemitriccus minor",
  "Hemithraupis guira",
  "Heterophasia picaoides",
  "Heterospingus xanthopygius",
  "Hylophylax naevius",
  "Ceuthmochares aereus",
  "Ceyx azureus",
  "Melanodryas vittata",
  "Melanopareia elegans",
  "Icterus gularis",
  "Icterus mesomelas",
  "Icterus leucopteryx",
  "Icterus pustulatus",
  "Icterus pyrrhopterus",
  "Inezia caudata",
  "Iole propinqua",
  "Irena cyanogastra",
  "Pycnonotus aurigaster",
  "Lagonosticta rufopicta",
  "Pycnonotus brunneus",
  "Lalage leucopyga",
  "Lalage nigra",
  "Lalage sharpei",
  "Laniarius bicolor",
  "Pycnonotus goiavier",
  "Laniocera rufescens",
  "Lanio fulvus",
  "Lanius collurioides",
  "Lathrotriccus euleri",
  "Amazona farinosa",
  "Lanius validirostris",
  "Lepidocolaptes souleyetii",
  "Lepidothrix coronata",
  "Lepidothrix iris",
  "Leptopogon amaurocephalus",
  "Coccycua minuta",
  "Egretta tricolor",
  "Lichenostomus cratitius",
  "Lichenostomus melanops",
  "Lichmera incana",
  "Lochmias nematura",
  "Lipaugus unirufus",
  "Lonchura atricapilla",
  "Lonchura striata",
  "Lonchura leucogastra",
  "Lonchura maja",
  "Lonchura punctulata",
  "Lonchura spectabilis",
  "Lophotriccus vitiosus",
  "Malimbus malimbicus",
  "Malimbus scutatus",
  "Malurus coronatus",
  "Malurus cyaneus",
  "Malurus leucopterus",
  "Malurus melanocephalus",
  "Macrosphenus flavicans",
  "Malia grata",
  "Manacus vitellinus",
  "Malacopteron affine",
  "Malacopteron cinereum",
  "Malacopteron magnum",
  "Malimbus erythrogaster",
  "Manorina flavigula",
  "Megalurus palustris",
  "Megarynchus pitangua",
  "Mayrornis lessoni",
  "Megabyas flammulatus",
  "Melanochlora sultanea",
  "Meliphaga lewinii",
  "Meliphaga notata",
  "Melithreptus albogularis",
  "Melithreptus brevirostris",
  "Melocichla mentalis",
  "Melozone crissalis",
  "Microbates cinereiventris",
  "Microbates collaris",
  "Microcerculus marginatus",
  "Microeca fascinans",
  "Microrhopias quixensis",
  "Mimus gundlachii",
  "Charadrius marginatus",
  "Mimus longicaudatus",
  "Mitrephanes phaeocercus",
  "Muscicapa adusta",
  "Myadestes occidentalis",
  "Myiagra caledonica",
  "Myiarchus ferox",
  "Myiagra ferrocyanea",
  "Myiagra vanikorensis",
  "Myiarchus nuttingi",
  "Myiarchus oberi",
  "Myiarchus sagrae",
  "Myiarchus yucatanensis",
  "Myiobius atricaudus",
  "Myiornis auricularis",
  "Myiornis ecaudatus",
  "Myophonus caeruleus",
  "Halcyon senegaloides",
  "Halcyon smyrnensis",
  "Myiozetetes cayanensis",
  "Myiozetetes granadensis",
  "Myiozetetes similis",
  "Myrmoborus leucophrys",
  "Myrmoborus myotherinus",
  "Myzomela rubratra",
  "Myrmothera campanisona",
  "Myrmotherula longipennis",
  "Myrmotherula menetriesii",
  "Myzomela albigula",
  "Myzomela boiei",
  "Myza celebensis",
  "Myza sarasinorum",
  "Myzomela eichhorni",
  "Myzomela erythrocephala",
  "Myzomela nigrita",
  "Myzomela pammelaena",
  "Neomixis tenella",
  "Neomixis viridis",
  "Hapalocrex flaviventer",
  "Nesocharis shelleyi",
  "Newtonia brunneicauda",
  "Niltava grandis",
  "Niltava macgrigoriae",
  "Atalotriccus pilaris",
  "Oenanthe pileata",
  "Onychognathus fulgidus",
  "Oreoica gutturalis",
  "Pycnonotus jocosus",
  "Accipiter erythrauchen",
  "Accipiter erythropus",
  "Pycnonotus luteolus",
  "Pycnonotus nieuwenhuisii",
  "Accipiter fasciatus",
  "Orthotomus atrogularis",
  "Orthotomus cinereiceps",
  "Orthotomus ruficeps",
  "Orthotomus sericeus",
  "Orthotomus sutorius",
  "Oxyruncus cristatus",
  "Pachycephala arctitorquis",
  "Oriolus sagittatus",
  "Oriolus xanthonotus",
  "Oriolus xanthornus",
  "Pachycephala lanioides",
  "Pachycephala monacha",
  "Pachycephala nudigula",
  "Pachycephala olivacea",
  "Pachycephalopsis hattamensis",
  "Pachyramphus aglaiae",
  "Accipiter francesiae",
  "Accipiter gentilis",
  "Pachyramphus albogriseus",
  "Pachyramphus castaneus",
  "Pachyramphus cinnamomeus",
  "Pachyramphus homochrous",
  "Pachyramphus marginatus",
  "Paradisaea raggiana",
  "Pachyramphus validus",
  "Paradisaea apoda",
  "Pardalotus rubricatus",
  "Kaupifalco monogrammicus",
  "Ketupa ketupu",
  "Ketupa zeylonensis",
  "Parus major",
  "Parus monticolus",
  "Lagopus muta",
  "Pellorneum fuscocapillus",
  "Ictinaetus malaiensis",
  "Pellorneum ruficeps",
  "Peneothello bimaculata",
  "Pericrocotus brevirostris",
  "Indicator willcocksi",
  "Pericrocotus igneus",
  "Perisoreus canadensis",
  "Petrochelidon rufocollaris",
  "Peucaea aestivalis",
  "Petroica rodinogaster",
  "Peucaea carpalis",
  "Peucaea ruficauda",
  "Irediparra gallinacea",
  "Phylloscopus cebuensis",
  "Phaenostictus mcleannani",
  "Ispidina picta",
  "Phainopepla nitens",
  "Phedina borbonica",
  "Philydor rufum",
  "Phlegopsis nigromaculata",
  "Hierococcyx varius",
  "Philydor erythrocercum",
  "Philydor erythropterum",
  "Pholidornis rushiae",
  "Phrygilus gayi",
  "Phylidonyris novaehollandiae",
  "Phylidonyris pyrrhopterus",
  "Pithys albifrons",
  "Phylloscopus herberti",
  "Phylloscopus trivirgatus",
  "Phytotoma rutila",
  "Brachygalba lugubris",
  "Pipraeidea melanonota",
  "Pipra aureola",
  "Edolisoma melas",
  "Pitta steerii",
  "Piranga roseogularis",
  "Pittasoma rufopileatum",
  "Pitta anerythra",
  "Pitta angolensis",
  "Pitta elegans",
  "Pitta iris",
  "Platyrinchus coronatus",
  "Platyrinchus platyrhynchos",
  "Prinia bairdii",
  "Platysteira cyanea",
  "Platysteira peltata",
  "Prinia polychroa",
  "Prinia rufescens",
  "Prinia socialis",
  "Prinia subflava",
  "Ploceus albinucha",
  "Prionochilus maculatus",
  "Prionochilus olivaceus",
  "Prionochilus percussus",
  "Prionochilus plateni",
  "Ploceus philippinus",
  "Ploceus sakalava",
  "Ploceus subaureus",
  "Pnoepyga pusilla",
  "Poecilodryas brachyura",
  "Poecilotriccus sylvia",
  "Stachyris leucotis",
  "Poephila acuticauda",
  "Stachyris maculata",
  "Stachyris nigriceps",
  "Pomatorhinus montanus",
  "Pomatorhinus schisticeps",
  "Pomatostomus temporalis",
  "Prinia crinigera",
  "Prinia hodgsonii",
  "Prinia inornata",
  "Dicrurus remifer",
  "Gavicalis virescens",
  "Prunella collaris",
  "Psalidoprocne nitens",
  "Psarocolius wagleri",
  "Psarisomus dalhousiae",
  "Hemipus picatus",
  "Psophodes nigrogularis",
  "Psophodes olivaceus",
  "Ptilonorhynchus violaceus",
  "Ptilorrhoa castanonota",
  "Pycnonotus xanthorrhous",
  "Pycnoptilus floccosus",
  "Pycnopygius ixoides",
  "Pyroderus scutatus",
  "Pyrrhula leucogenis",
  "Pytilia melba",
  "Quiscalus major",
  "Rhynchocyclus brevirostris",
  "Ramphocelus bresilius",
  "Ramphocelus carbo",
  "Rhabdornis mystacalis",
  "Rhytipterna holerythra",
  "Rhipidura atra",
  "Rhipidura aureola",
  "Rhipidura dahli",
  "Rhipidura leucothorax",
  "Rhipidura nebulosa",
  "Rhipidura nigrocinnamomea",
  "Rhipidura threnothorax",
  "Saltator atriceps",
  "Lepidopyga goudoti",
  "Sakesphorus luctuosus",
  "Salpinctes obsoletus",
  "Saltator albicollis",
  "Saltator aurantiirostris",
  "Saltator grossus",
  "Saltator maximus",
  "Saxicola caprata",
  "Saxicola gutturalis",
  "Erythropitta granatina",
  "Sarcops calvus",
  "Malacoptila rufa",
  "Scelorchilus rubecula",
  "Sclateria naevia",
  "Sclerurus guatemalensis",
  "Melanerpes superciliaris",
  "Melanerpes uropygialis",
  "Semioptera wallacii",
  "Sericornis citreogularis",
  "Sericornis frontalis",
  "Sericornis humilis",
  "Sericornis magnirostra",
  "Sitta frontalis",
  "Sitta azurea",
  "Sitta villosa",
  "Spizixos semitorques",
  "Stachyris thoracica",
  "Stagonopleura bella",
  "Stelgidopteryx ruficollis",
  "Sporophila americana",
  "Sylvietta denti",
  "Synallaxis frontalis",
  "Sporophila intermedia",
  "Synallaxis gujanensis",
  "Sporophila minuta",
  "Sporophila peruviana",
  "Stipiturus malachurus",
  "Strepera fuliginosa",
  "Strepera graculina",
  "Struthidea cinerea",
  "Ninox boobook",
  "Sublegatus modestus",
  "Sylvietta ruficapilla",
  "Sylvietta virens",
  "Sylvietta whytii",
  "Synallaxis rutilans",
  "Synallaxis albescens",
  "Merops gularis",
  "Merops leschenaulti",
  "Synallaxis brachyura",
  "Synallaxis candei",
  "Synallaxis cinnamomea",
  "Syndactyla rufosuperciliata",
  "Taeniopygia bichenovii",
  "Caloenas nicobarica",
  "Caloperdix oculeus",
  "Caloramphus fuliginosus",
  "Caloramphus hayii",
  "Pogoniulus bilineatus",
  "Tangara cyanocephala",
  "Tangara inornata",
  "Taraba major",
  "Thamnophilus punctatus",
  "Tchagra australis",
  "Tchagra senegalus",
  "Teretistris fornsi",
  "Terpsiphone bourbonnensis",
  "Terpsiphone mutata",
  "Terpsiphone viridis",
  "Tersina viridis",
  "Thamnomanes ardesiacus",
  "Thamnomanes caesius",
  "Thamnophilus amazonicus",
  "Thamnophilus caerulescens",
  "Thamnophilus murinus",
  "Thamnophilus palliatus",
  "Thamnophilus schistaceus",
  "Thlypopsis sordida",
  "Tregellasia capito",
  "Phapitreron amethystinus",
  "Timalia pileata",
  "Timeliopsis griseigula",
  "Tityra inquisitor",
  "Todirostrum chrysocrotaphum",
  "Todirostrum cinereum",
  "Todirostrum maculatum",
  "Tolmomyias poliocephalus",
  "Toxostoma lecontei",
  "Toxostoma longirostre",
  "Toxostoma redivivum",
  "Chloroceryle americana",
  "Tricholestes criniger",
  "Trochocercus nitens",
  "Turdoides affinis",
  "Pogoniulus scolopaceus",
  "Turdus bewsheri",
  "Turdus falcklandii",
  "Chlorostilbon canivetii",
  "Turdus fumigatus",
  "Turdus pelios",
  "Turdus rufiventris",
  "Tyrannus melancholicus",
  "Ardea sumatrana",
  "Ardeola speciosa",
  "Upucerthia dumetaria",
  "Uraeginthus angolensis",
  "Psitteuteles iris",
  "Vireolanius eximius",
  "Vireolanius pulchellus",
  "Cecropis senegalensis",
  "Vireo magister",
  "Xanthotis polygrammus",
  "Larus pacificus",
  "Xenerpestes minlosi",
  "Xiphocolaptes promeropirhynchus",
  "Xiphorhynchus obsoletus",
  "Xolmis cinereus",
  "Thalassornis leuconotus",
  "Thalurania colombica",
  "Zosterops hypoxanthus",
  "Zoothera heinei",
  "Zoothera lunulata",
  "Thalurania furcata",
  "Zosterops atricapilla",
  "Zosterops atrifrons",
  "Zosterops flavifrons",
  "Zosterops griseotinctus",
  "Zosterops metcalfii",
  "Zosterops kulambangrae",
  "Zosterops lateralis",
  "Zosterops luteus",
  "Streptoprocne biscutata",
  "Zosterops novaeguineae",
  "Conopophaga aurita",
  "Cracticus torquatus",
  "Accipiter albogularis",
  "Accipiter butleri",
  "Accipiter melanoleucus",
  "Coccyzus merlini",
  "Accipiter rhodogaster",
  "Accipiter hiogaster",
  "Accipiter superciliosus",
  "Actenoides concretus",
  "Actenoides lindsayi",
  "Actenoides princeps",
  "Aegolius funereus",
  "Aechmophorus clarkii",
  "Aegotheles albertisi",
  "Aegotheles bennettii",
  "Aegotheles cristatus",
  "Aegotheles wallacii",
  "Aerodramus orientalis",
  "Aerodramus francicus",
  "Aerodramus fuciphagus",
  "Aerodramus hirundinaceus",
  "Aerodramus inquietus",
  "Aerodramus maximus",
  "Aerodramus whiteheadi",
  "Aerodramus salangana",
  "Aerodramus spodiopygius",
  "Phapitreron leucotis",
  "Alisterus amboinensis",
  "Alisterus chloropterus",
  "Alisterus scapularis",
  "Alopecoenas beccarii",
  "Aeronautes saxatalis",
  "Agapornis pullarius",
  "Phodilus badius",
  "Crypturellus soui",
  "Crypturellus tataupa",
  "Alcedo meninting",
  "Alcedo quadribrachys",
  "Alectoris barbara",
  "Cinnyris jugularis",
  "Alectroenas sganzini",
  "Alopecoenas jobiensis",
  "Amaurolimnas concolor",
  "Amazilia amazilia",
  "Buceros hydrocorax",
  "Amaurornis moluccana",
  "Amaurornis phoenicurus",
  "Amazilia brevirostris",
  "Amazilia candida",
  "Amazilia tzacatl",
  "Amazilia versicolor",
  "Amazilia violiceps",
  "Amazilia cyanura",
  "Amazilia yucatanensis",
  "Amazilia edward",
  "Amazilia fimbriata",
  "Buceros rhinoceros",
  "Amazilia leucogaster",
  "Amazilia rutila",
  "Amazilia saucerottei",
  "Amazilia tobaci",
  "Cochlearius cochlearius",
  "Cynanthus latirostris",
  "Amazona auropalliata",
  "Amazona vittata",
  "Amazonetta brasiliensis",
  "Anastomus lamelligerus",
  "Anas georgica",
  "Anas bahamensis",
  "Anas gracilis",
  "Anas eatoni",
  "Anas poecilorhyncha",
  "Anas sparsa",
  "Anas superciliosa",
  "Anous stolidus",
  "Anous tenuirostris",
  "Anthracoceros albirostris",
  "Antigone antigone",
  "Antrostomus cubanensis",
  "Apaloderma narina",
  "Apaloderma vittatum",
  "Aprosmictus erythropterus",
  "Aprosmictus jonquillaceus",
  "Apus balstoni",
  "Aquila audax",
  "Aramus guarauna",
  "Arborophila charltonii",
  "Arborophila chloropus",
  "Ara macao",
  "Arborophila javanica",
  "Argusianus argus",
  "Asio clamator",
  "Asio stygius",
  "Athene brama",
  "Athene cunicularia",
  "Aviceda cuculoides",
  "Aviceda jerdoni",
  "Aviceda subcristata",
  "Bubo nipalensis",
  "Bubo philippensis",
  "Batrachostomus cornutus",
  "Batrachostomus septimus",
  "Biziura lobata",
  "Blythipicus pyrrhotis",
  "Bolbopsittacus lunulatus",
  "Burhinus vermiculatus",
  "Bostrychia hagedash",
  "Bostrychia olivacea",
  "Botaurus pinnatus",
  "Busarellus nigricollis",
  "Brotogeris chrysoptera",
  "Brotogeris jugularis",
  "Brotogeris sanctithomae",
  "Bubo bubo",
  "Bubo coromandus",
  "Bubo sumatranus",
  "Burhinus bistriatus",
  "Buteogallus anthracinus",
  "Buteo nitidus",
  "Chionis minor",
  "Bycanistes fistulator",
  "Cacatua pastinator",
  "Cacomantis aeruginosus",
  "Cacomantis castaneiventris",
  "Cacomantis flabelliformis",
  "Campephilus melanoleucos",
  "Cacomantis sonneratii",
  "Cacomantis variolosus",
  "Campethera cailliautii",
  "Campethera nivosa",
  "Calyptorhynchus banksii",
  "Calyptorhynchus lathami",
  "Campephilus guatemalensis",
  "Campephilus rubricollis",
  "Campethera abingoni",
  "Caprimulgus natalensis",
  "Campethera tullbergi",
  "Caprimulgus nubicus",
  "Caprimulgus pectoralis",
  "Caracara cheriway",
  "Capito maculicoronatus",
  "Caprimulgus affinis",
  "Caprimulgus asiaticus",
  "Caprimulgus atripennis",
  "Caprimulgus celebensis",
  "Centropus leucogaster",
  "Centropus melanops",
  "Centropus menbeki",
  "Centropus milo",
  "Centropus monachus",
  "Caprimulgus climacurus",
  "Caprimulgus fossii",
  "Caprimulgus indicus",
  "Caprimulgus macrurus",
  "Caprimulgus madagascariensis",
  "Centropus phasianinus",
  "Centropus senegalensis",
  "Centropus sinensis",
  "Caprimulgus pulchellus",
  "Cathartes burrovianus",
  "Celeus elegans",
  "Celeus flavus",
  "Celeus loricatus",
  "Centropus bengalensis",
  "Centropus bernsteini",
  "Centropus celebensis",
  "Centropus superciliosus",
  "Centropus toulou",
  "Centropus viridis",
  "Ceyx erithaca",
  "Ceyx pusillus",
  "Chaetocercus jourdanii",
  "Chaetura brachyura",
  "Chaetura cinereiventris",
  "Chrysococcyx xanthorhynchus",
  "Chrysocolaptes festivus",
  "Chrysocolaptes guttacristatus",
  "Cyornis hainanus",
  "Artamus cinereus",
  "Acridotheres tristis",
  "Acrocephalus australis",
  "Schoeniparus brunneus",
  "Alcippe poioicephala",
  "Anthornis melanura",
  "Asthenes pyrrholeuca",
  "Attila spadiceus",
  "Clibanornis rubiginosus",
  "Automolus rufipileatus",
  "Baeolophus inornatus",
  "Horornis acanthizoides",
  "Certhiasomus stictolaemus",
  "Certhia familiaris",
  "Chiroxiphia pareola",
  "Horornis fortipes",
  "Climacteris melanurus",
  "Copsychus saularis",
  "Coracina caeruleogrisea",
  "Coracina macei",
  "Cyornis tickelliae",
  "Dendrexetastes rufigula",
  "Dendrocincla homochroa",
  "Dendrocolaptes picumnus",
  "Dendrocolaptes platyrostris",
  "Dendroplex picus",
  "Dicaeum agile",
  "Dicaeum anthonyi",
  "Dicrurus bracteatus",
  "Dumetia hyperythra",
  "Dysithamnus mentalis",
  "Formicivora rufa",
  "Emberiza cia",
  "Epinecrophylla leucophthalma",
  "Erythrura cyaneovirens",
  "Eumyias indigo",
  "Ficedula dumetoria",
  "Galerida theklae",
  "Ficedula hyperythra",
  "Fluvicola nengeta",
  "Grallaria varia",
  "Hemitriccus margaritaceiventer",
  "Heinrichia calligyna",
  "Hemitriccus zosterops",
  "Cecropis abyssinica",
  "Hylopezus dives",
  "Horornis flavolivaceus",
  "Iole viridescens",
  "Lagonosticta rubricata",
  "Lepidocolaptes angustirostris",
  "Leiothrix lutea",
  "Mimus polyglottos",
  "Spermestes bicolor",
  "Lophotriccus pileatus",
  "Loxia curvirostra",
  "Montifringilla nivalis",
  "Phyllergates cucullatus",
  "Saxicola ferreus",
  "Amazona leucocephala",
  "Anhinga rufa",
  "Ceryle rudis",
  "Cyornis omissus",
  "Acanthisitta chloris",
  "Alcippe brunneicauda",
  "Locustella mandelli",
  "Chamaeza campanisona",
  "Cicinnurus magnificus",
  "Empidonomus varius",
  "Furnarius figulus",
  "Gerygone sulphurea",
  "Grallaria guatimalensis",
  "Myiomela leucura",
  "Conopias trivirgatus",
  "Crateroscelis murina",
  "Drymophila squamata",
  "Accipiter gundlachi",
  "Amazilia lactea",
  "Chaetura spinicaudus",
  "Piaya cayana",
  "Ptilinopus rivoli",
  "Dinopium javanense",
  "Dryobates scalaris",
  "Gyps fulvus",
  "Otus elegans",
  "Pachycephala simplex",
  "Batis erlangeri",
  "Acanthornis magna",
  "Acrocephalus rufescens",
  "Apalis cinerea",
  "Apalis melanocephala",
  "Baeolophus atricristatus",
  "Auriparus flaviceps",
  "Bathmocercus rufus",
  "Xanthomixis zosterops",
  "Alaudala raytal",
  "Cicinnurus regius",
  "Cisticola brachypterus",
  "Cisticola natalensis",
  "Colluricincla megarhyncha",
  "Coracina lineata",
  "Edolisoma schisticeps",
  "Cracticus cassicus",
  "Cyanocitta stelleri",
  "Donacobius atricapilla",
  "Elminia longicauda",
  "Hyliota violacea",
  "Hemitriccus griseipectus",
  "Hylophilus semicinereus",
  "Phonygammus keraudrenii",
  "Poecile palustris",
  "Symposiachrus axillaris",
  "Atticora tibialis",
  "Periparus ater",
  "Poecile atricapillus",
  "Poecile gambeli",
  "Sittiparus semilarvatus",
  "Arses telescopthalmus",
  "Cisticola brunnescens",
  "Cisticola marginatus",
  "Corvus enca",
  "Corvus orru",
  "Drymodes beccarii",
  "Garrulus glandarius",
  "Microeca flavigaster",
  "Machetornis rixosa",
  "Monarcha cinerascens",
  "Myzomela chloroptera",
  "Pachycephala mentalis",
  "Pachycephala pectoralis",
  "Pachyramphus polychopterus",
  "Cyanistes caeruleus",
  "Piprites chloris",
  "Psalidoprocne pristoptera",
  "Myrmelastes leucostigma",
  "Campephaga quiscalina",
  "Poodytes gramineus",
  "Carterornis chrysomela",
  "Symposiachrus trivirgatus",
  "Myzomela obscura",
  "Melaniparus leucomelas",
  "Hydrornis caeruleus",
  "Terpsiphone rufiventer",
  "Acanthiza chrysorrhoa",
  "Alaemon alaudipes",
  "Anthochaera chrysoptera",
  "Aphelocephala leucopsis",
  "Aphrastura spinicauda",
  "Artamus minor",
  "Batis minor",
  "Clytorhynchus vitiensis",
  "Cnemotriccus fuscatus",
  "Conopophila albogularis",
  "Coracina papuensis",
  "Cyanocorax yncas",
  "Eremomela badiceps",
  "Eremopterix nigriceps",
  "Gerygone chrysogaster",
  "Gerygone mouki",
  "Glycichaera fallax",
  "Glyphorynchus spirurus",
  "Hirundo neoxena",
  "Hypothymis helenae",
  "Lalage maculosa",
  "Lanius vittatus",
  "Machaerirhynchus flaviventer",
  "Malurus cyanocephalus",
  "Manucodia ater",
  "Manucodia comrii",
  "Melanocharis nigra",
  "Melilestes megarhynchus",
  "Meliphaga aruensis",
  "Mirafra rufocinnamomea",
  "Myiagra alecto",
  "Myiagra ruficollis",
  "Myiarchus panamensis",
  "Myiarchus stolidus",
  "Myzomela cardinalis",
  "Neopipo cinnamomea",
  "Oedistoma pygmaeum",
  "Oriolus flavocinctus",
  "Orthonyx spaldingii",
  "Orthotomus derbianus",
  "Orthotomus frontalis",
  "Orthotomus sepium",
  "Pachycephala soror",
  "Pachycephala griseonota",
  "Pachycephala melanura",
  "Pachycephala philippinensis",
  "Paradisaea minor",
  "Pardalotus striatus",
  "Philemon argenticeps",
  "Phyllomyias fasciatus",
  "Phylloscartes ventralis",
  "Edolisoma mindanense",
  "Pitohui dichrous",
  "Prinia sylvatica",
  "Poecilodryas hypoleuca",
  "Prinia familiaris",
  "Prionops scopifrons",
  "Prosthemadera novaeseelandiae",
  "Pseudhirundo griseopyga",
  "Rhipidura hyperythra",
  "Rhipidura leucophrys",
  "Rhipidura rufidorsa",
  "Rhipidura teysmanni",
  "Sericornis spilodera",
  "Serpophaga hypoleuca",
  "Sphecotheres vieilloti",
  "Strepera versicolor",
  "Sublegatus arenarum",
  "Thamnophilus doliatus",
  "Vireo huttoni",
  "Cecropis semirufa",
  "Vireo pallens",
  "Xanthotis flaviventer",
  "Elaenia martinica",
  "Capsiempis flaveola",
  "Corvus corone",
  "Cinclosoma punctatum",
  "Myiagra galeata",
  "Notiomystis cincta",
  "Melanodryas cucullata",
  "Anthracothorax prevostii",
  "Antrostomus rufus",
  "Ammomanes deserti",
  "Agelaius humeralis",
  "Amblyospiza albifrons",
  "Chamaetylas poliocephala",
  "Ammodramus humeralis",
  "Eurillas gracilis",
  "Andropadus importunus",
  "Eurillas virens",
  "Anomalospiza imberbis",
  "Anthus pallidiventris",
  "Aplonis feadensis",
  "Arremonops chloronotus",
  "Myiothlypis flaveola",
  "Basileuterus rufifrons",
  "Haemorhous mexicanus",
  "Caryothraustes canadensis",
  "Cercotrichas podobe",
  "Chrysomus icterocephalus",
  "Chrysomus ruficapillus",
  "Conirostrum speciosum",
  "Coryphospingus pileatus",
  "Criniger barbatus",
  "Criniger calurus",
  "Cyanerpes lucidus",
  "Cyornis poliogenys",
  "Dicaeum geelvinkianum",
  "Zosterops maderaspatanus",
  "Erythrura hyperythra",
  "Estrilda astrild",
  "Eucometis penicillata",
  "Hylia prasina",
  "Euphonia hirundinacea",
  "Euphonia laniirostris",
  "Euplectes afer",
  "Euphonia minuta",
  "Euplectes axillaris",
  "Habia rubica",
  "Henicorhina leucosticta",
  "Hypsipetes philippinus",
  "Melozone fusca",
  "Fraseria plumbea",
  "Bradornis fuliginosus",
  "Leptocoma aspasia",
  "Cyanomitra cyanolaema",
  "Chalcomitra fuliginosa",
  "Cinnyris johannae",
  "Cyanomitra olivacea",
  "Anthreptes seimundi",
  "Chalcomitra senegalensis",
  "Cinnyris superbus",
  "Cinnyris venustus",
  "Suthora verreauxi",
  "Sinosuthora webbiana",
  "Cyornis ruficauda",
  "Crithagra mozambica",
  "Crithagra rufobrunnea",
  "Sterrhoptilus capitalis",
  "Cyanoderma melanothorax",
  "Leistes bellicosus",
  "Pheugopedius felix",
  "Melanospiza bicolor",
  "Cantorchilus leucotis",
  "Cantorchilus longirostris",
  "Pheugopedius maculipectus",
  "Thryophilus rufalbus",
  "Geokichla peronii",
  "Arachnothera flammifera",
  "Ficedula luzoniensis",
  "Mixornis bornensis",
  "Sitta europaea",
  "Turdus mandarinus",
  "Calyptophilus frugivorus",
  "Sporophila plumbea",
  "Eurillas ansorgei",
  "Aplonis grandis",
  "Arachnothera clarae",
  "Campylorhynchus griseus",
  "Cardinalis cardinalis",
  "Spinus psaltria",
  "Cinclus cinclus",
  "Cinnyricinclus leucogaster",
  "Dives warczewiczi",
  "Fraseria cinerascens",
  "Cinnyris cupreus",
  "Leistes loyca",
  "Pheugopedius genibarbis",
  "Pheugopedius coraya",
  "Geokichla erythronota",
  "Leptocoma sperata",
  "Thryothorus ludovicianus",
  "Emberiza cirlus",
  "Zosterops chloris",
  "Aethopyga bella",
  "Agelasticus cyanopus",
  "Agelasticus thilius",
  "Aimophila ruficeps",
  "Alethe castanea",
  "Amphispiza bilineata",
  "Anthus novaeseelandiae",
  "Aplonis tabuensis",
  "Arremonops conirostris",
  "Arremonops rufivirgatus",
  "Tiaris olivaceus",
  "Cissopis leverianus",
  "Campylorhynchus fasciatus",
  "Catharus aurantiirostris",
  "Cinclocerthia ruficauda",
  "Conirostrum bicolor",
  "Coryphospingus cucullatus",
  "Cossypha cyanocampter",
  "Cyphorhinus phaeocephalus",
  "Dicaeum celebicum",
  "Diuca diuca",
  "Emberizoides herbicola",
  "Sporophila schistacea",
  "Enicurus scouleri",
  "Erythrura trichroa",
  "Euphonia chlorotica",
  "Euphonia cyanocephala",
  "Garrulax canorus",
  "Garrulax castanotis",
  "Garrulax palliatus",
  "Hemithraupis flavicollis",
  "Hypsipetes madagascariensis",
  "Icterus nigrogularis",
  "Icterus prosthemelas",
  "Illadopsis cleaveri",
  "Illadopsis puveli",
  "Pycnonotus barbatus",
  "Lampropsar tanagrinus",
  "Lamprotornis splendidus",
  "Loxigilla noctis",
  "Linurgus olivaceus",
  "Lonchura melaena",
  "Lonchura tristissima",
  "Lonchura kelaarti",
  "Lonchura pallida",
  "Malimbus rubricollis",
  "Malacopteron albogulare",
  "Margarops fuscatus",
  "Mandingoa nitidula",
  "Melaenornis pammelaina",
  "Microcerculus bambla",
  "Microligea palustris",
  "Mimus gilvus",
  "Mimus parvulus",
  "Mimus saturninus",
  "Mino anais",
  "Molothrus bonariensis",
  "Molothrus oryzivorus",
  "Motacilla aguimp",
  "Motacilla clara",
  "Muscicapa aquatica",
  "Peucaea botterii",
  "Nemosia pileata",
  "Pheucticus chrysogaster",
  "Neocossyphus poensis",
  "Nigrita luteifrons",
  "Nigrita bicolor",
  "Nigrita canicapillus",
  "Nigrita fusconotus",
  "Oenanthe moesta",
  "Ortygospiza atricollis",
  "Parmoptila woodhousei",
  "Passer griseus",
  "Passerina versicolor",
  "Phaenicophilus poliocephalus",
  "Pinicola enucleator",
  "Ploceus aurantius",
  "Ploceus bicolor",
  "Ploceus pelzelni",
  "Ploceus tricolor",
  "Ploceus vitellinus",
  "Polioptila albiloris",
  "Polioptila nigriceps",
  "Oenanthe familiaris",
  "Psaltriparus minimus",
  "Psarocolius decumanus",
  "Ptilocichla mindanensis",
  "Quiscalus lugubris",
  "Pyrrhula erythaca",
  "Quelea quelea",
  "Quiscalus mexicanus",
  "Quiscalus niger",
  "Ramphocaenus melanurus",
  "Ramphocelus dimidiatus",
  "Ramphocelus sanguinolentus",
  "Schistochlamys melanopis",
  "Sheppardia cyornithopsis",
  "Sicalis columbiana",
  "Sicalis flaveola",
  "Sicalis luteola",
  "Sitta solangiae",
  "Sitta neumayer",
  "Sitta oenochlamys",
  "Spermophaga haematina",
  "Sporophila bouvronides",
  "Sporophila caerulescens",
  "Sporophila leucoptera",
  "Tangara gyrola",
  "Tangara lavinia",
  "Toxostoma cinereum",
  "Toxostoma curvirostre",
  "Thryomanes bewickii",
  "Turdoides jardineii",
  "Turdus flavipes",
  "Turdus grayi",
  "Turdus leucomelas",
  "Turdus nudigenis",
  "Uropsila leucogastra",
  "Zonotrichia capensis",
  "Zosterops nigrorum",
  "Zosterops semperi",
  "Zosterops senegalensis",
  "Brachypteryx montana",
  "Coryphaspiza melanotis",
  "Dicaeum everetti",
  "Baeopogon indicator",
  "Eurillas latirostris",
  "Phylloscopus montis",
  "Scotocerca inquieta",
  "Urosphena subulata",
  "Pycnonotus leucotis",
  "Polioptila californica",
  "Polioptila melanura",
  "Aplonis metallica",
  "Aplonis striata",
  "Aplonis mysolensis",
  "Melanotis caerulescens",
  "Allenia fusca",
  "Eumyias panayensis",
  "Dicaeum aureolimbatum",
  "Neochmia ruficauda",
  "Leucosticte arctoa",
  "Aerodramus vanikorensis",
  "Agapornis canus",
  "Alectoris graeca",
  "Alectoris rufa",
  "Alectura lathami",
  "Amazona albifrons",
  "Amazona amazonica",
  "Amazona autumnalis",
  "Amazona ochrocephala",
  "Amazona oratrix",
  "Bonasa umbellus",
  "Bubo virginianus",
  "Cacatua galerita",
  "Cacatua sanguinea",
  "Cacatua sulphurea",
  "Callipepla californica",
  "Callipepla douglasii",
  "Callipepla gambelii",
  "Cereopsis novaehollandiae",
  "Chalcophaps stephani",
  "Colinus cristatus",
  "Columbina passerina",
  "Corvus splendens",
  "Crithagra flaviventris",
  "Cyanoramphus novaezelandiae",
  "Dendrocygna arcuata",
  "Dicaeum eximium",
  "Dromaius novaehollandiae",
  "Eolophus roseicapilla",
  "Eos bornea",
  "Eupsittula canicularis",
  "Eupsittula pertinax",
  "Falco femoralis",
  "Forpus passerinus",
  "Francolinus francolinus",
  "Francolinus pondicerianus",
  "Gallicolumba tristigmata",
  "Gallirallus australis",
  "Grallina cyanoleuca",
  "Gymnorhina tibicen",
  "Icterus icterus",
  "Icterus pectoralis",
  "Lagopus leucura",
  "Leptotila jamaicensis",
  "Lonchura castaneothorax",
  "Manorina melanocephala",
  "Meleagris gallopavo",
  "Menura novaehollandiae",
  "Myiopsitta monachus",
  "Neochmia temporalis",
  "Nothoprocta perdicaria",
  "Numida meleagris",
  "Oenanthe leucura",
  "Ortalis vetula",
  "Perdicula asiatica",
  "Philemon cockerelli",
  "Pitangus sulphuratus",
  "Platycercus elegans",
  "Ploceus cucullatus",
  "Ploceus intermedius",
  "Ploceus melanocephalus",
  "Ploceus velatus",
  "Prosopeia tabuensis",
  "Psittacara holochlorus",
  "Psittacara mitratus",
  "Psittacula krameri",
  "Psittacus erithacus",
  "Pternistis afer",
  "Pterocles exustus",
  "Ptilinopus insolitus",
  "Pycnonotus cafer",
  "Rhea pennata",
  "Sephanoides fernandensis",
  "Serinus canicollis",
  "Sporophila angolensis",
  "Streptopelia capicola",
  "Struthio camelus",
  "Sturnia erythropygia",
  "Tanygnathus lucionensis",
  "Trichoglossus haematodus",
  "Turdus lherminieri",
  "Tyto novaehollandiae",
  "Uraeginthus bengalus",
  "Illadopsis fulvescens",
  "Megapodius forsteni",
  "Arborophila hyperythra",
  "Rheinardia ocellata",
  "Streptopelia picturata",
  "Streptopelia chinensis",
  "Macropygia doreya",
  "Macropygia modiglianii",
  "Leptotila plumbeiceps",
  "Treron seimundi",
  "Ptilinopus occipitalis",
  "Ptilinopus merrilli",
  "Ptilinopus fischeri",
  "Ptilinopus leclancheri",
  "Ptilinopus bernsteinii",
  "Ptilinopus magnificus",
  "Ptilinopus victor",
  "Eudynamys melanorhynchus",
  "Chrysococcyx megarhynchus",
  "Chrysococcyx minutillus",
  "Collocalia affinis",
  "Collocalia marginata",
  "Collocalia isonota",
  "Collocalia sumbawae",
  "Collocalia neglecta",
  "Collocalia uropygialis",
  "Aerodramus terraereginae",
  "Aerodramus brevirostris",
  "Aerodramus amelis",
  "Aerodramus ocistus",
  "Aerodramus germani",
  "Gallirallus castaneoventris",
  "Gallirallus philippensis",
  "Gallirallus torquatus",
  "Mustelirallus albicollis",
  "Mustelirallus erythrops",
  "Porphyrio melanotus",
  "Porphyrio poliocephalus",
  "Chroicocephalus novaehollandiae",
  "Anous albivitta",
  "Phalacrocorax pelagicus",
  "Phalacrocorax brasilianus",
  "Phalacrocorax auritus",
  "Phalacrocorax atriceps",
  "Butorides virescens",
  "Threskiornis molucca",
  "Haliaeetus humilis",
  "Ceyx rufidorsa",
  "Todiramphus sacer",
  "Todiramphus sordidus",
  "Todiramphus albicilla",
  "Todiramphus tristrami",
  "Psilopogon eximius",
  "Yungipicus maculatus",
  "Yungipicus nanus",
  "Yungipicus moluccensis",
  "Yungipicus canicapillus",
  "Dryobates villosus",
  "Dryobates kirkii",
  "Reinwardtipicus validus",
  "Calyptorhynchus funereus",
  "Lophochroa leadbeateri",
  "Polytelis anthopeplus",
  "Ailuroedus geislerorum",
  "Ailuroedus arfakianus",
  "Meliphaga analoga",
  "Meliphaga montana",
  "Meliphaga mimikae",
  "Meliphaga flavirictus",
  "Meliphaga cinereifrons",
  "Sericornis virgatus",
  "Hylacola cauta",
  "Pomatostomus isidorei",
  "Pericrocotus speciosus",
  "Coracina cucullata",
  "Analisoma coerulescens",
  "Pachycephala chlorura",
  "Pachycephala citreogaster",
  "Pachycephala collaris",
  "Pachycephala vanikorensis",
  "Pachycephala macrorhyncha",
  "Turnagra capensis",
  "Artamus leucorynchus",
  "Cracticus quoyi",
  "Pomarea mendozae",
  "Microeca flavovirescens",
  "Eopsaltria pulverulenta",
  "Periparus rubidiventris",
  "Periparus elegans",
  "Lophophanes dichrous",
  "Acrocephalus musae",
  "Cincloramphus rufus",
  "Brachypodius urostictus",
  "Rubigula erythropthalmos",
  "Rubigula cyaniventris",
  "Rubigula squamata",
  "Iole indica",
  "Urosphena pallidipes",
  "Horornis vulcanius",
  "Lophozosterops javanicus",
  "Lophozosterops squamiceps",
  "Lophozosterops goodfellowi",
  "Lophozosterops superciliaris",
  "Lophozosterops dohertyi",
  "Chlorocharis emiliae",
  "Zosterops ugiensis",
  "Pellorneum pyrrogenys",
  "Pellorneum malaccense",
  "Pellorneum rostratum",
  "Pellorneum celebense",
  "Turdinus abbotti",
  "Turdinus sepiarius",
  "Ianthocincla mitrata",
  "Copsychus fulicatus",
  "Copsychus malabaricus",
  "Copsychus luzoniensis",
  "Cyanomitra veroxii",
  "Lagonosticta senegala",
  "Erythrura regia",
  "Melopyrrha portoricensis",
  "Melopyrrha violacea",
  "Camarhynchus pallidus",
  "Camarhynchus psittacula",
  "Camarhynchus parvulus",
  "Geospiza propinqua"
)

resident <- resident %>% filter(SCINAME %in% list_outliers)

zlat <- sp1.4 %>% filter(SCINAME=="Zosterops lateralis"| SCINAME=="Dulus dominicus" | SCINAME== "Larus hartlaubii")

resident_npoly <- calculateIntersect(zlat, land)

##Remove those list objects that are empty (e.g. seabirds that haven't intersected with an island)
resident_npoly_complete <- list()
for (i in resident_npoly){
  if(length(i$OBJECTID)>0){
    resident_npoly_complete[[as.character(unique(i$SCINAME))]] <- i
  }
}

resident_npoly_complete

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio1, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na()
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      ann_mean_temp_mean = mean(species),
      ann_mean_temp_sd = sd(species),
      ann_mean_temp_max = max(species),
      ann_mean_temp_min = min(species),
      ann_mean_temp_median = median(species)
    )
}

bio1 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio1) <- colnames(result$`Dulus dominicus`)
rownames(bio1) <- names(result)
bio1 <- bio1 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio2, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      mean_diurnal_range_mean = mean(species),
      mean_diurnal_range_sd = sd(species),
      mean_diurnal_range_max = max(species),
      mean_diurnal_range_min = min(species),
      mean_diurnal_range_median = median(species)
    )
}

bio2 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio2) <- colnames(result$`Dulus dominicus`)
rownames(bio2) <- names(result)
bio2 <- bio2 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio3, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      isothermality_mean = mean(species),
      isothermality_sd = sd(species),
      isothermality_max = max(species),
      isothermality_min = min(species),
      isothermality_median = median(species)
    )
}

bio3 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio3) <- colnames(result$`Dulus dominicus`)
rownames(bio3) <- names(result)
bio3 <- bio3 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio4, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      temp_seasonality_mean = mean(species),
      temp_seasonality_sd = sd(species),
      temp_seasonality_max = max(species),
      temp_seasonality_min = min(species),
      temp_seasonality_median = median(species)
    )
}

bio4 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio4) <- colnames(result$`Dulus dominicus`)
rownames(bio4) <- names(result)
bio4 <- bio4 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio5, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      max_temp_warm_mean = mean(species),
      max_temp_warm_sd = sd(species),
      max_temp_warm_max = max(species),
      max_temp_warm_min = min(species),
      max_temp_warm_median = median(species)
    )
}

bio5 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio5) <- colnames(result$`Dulus dominicus`)
rownames(bio5) <- names(result)
bio5 <- bio5 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio6, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      min_temp_cold_mean = mean(species),
      min_temp_cold_sd = sd(species),
      min_temp_cold_max = max(species),
      min_temp_cold_min = min(species),
      min_temp_cold_median = median(species)
    )
}

bio6 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio6) <- colnames(result$`Dulus dominicus`)
rownames(bio6) <- names(result)
bio6 <- bio6 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio7, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      temp_annual_range_mean = mean(species),
      temp_annual_range_sd = sd(species),
      temp_annual_range_max = max(species),
      temp_annual_range_min = min(species),
      temp_annual_range_median = median(species)
    )
}

bio7 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio7) <- colnames(result$`Dulus dominicus`)
rownames(bio7) <- names(result)
bio7 <- bio7 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio8, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      mean_temp_wet_mean = mean(species),
      mean_temp_wet_sd = sd(species),
      mean_temp_wet_max = max(species),
      mean_temp_wet_min = min(species),
      mean_temp_wet_median = median(species)
    )
}

bio8 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio8) <- colnames(result$`Dulus dominicus`)
rownames(bio8) <- names(result)
bio8 <- bio8 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio9, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      mean_temp_dry_mean = mean(species),
      mean_temp_dry_sd = sd(species),
      mean_temp_dry_max = max(species),
      mean_temp_dry_min = min(species),
      mean_temp_dry_median = median(species)
    )
}

bio9 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio9) <- colnames(result$`Dulus dominicus`)
rownames(bio9) <- names(result)
bio9 <- bio9 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio10, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      mean_temp_warm_mean = mean(species),
      mean_temp_warm_sd = sd(species),
      mean_temp_warm_max = max(species),
      mean_temp_warm_min = min(species),
      mean_temp_warm_median = median(species)
    )
}

bio10 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio10) <- colnames(result$`Dulus dominicus`)
rownames(bio10) <- names(result)
bio10 <- bio10 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio11, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na()
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      mean_temp_cold_mean = mean(species),
      mean_temp_cold_sd = sd(species),
      mean_temp_cold_max = max(species),
      mean_temp_cold_min = min(species),
      mean_temp_cold_median = median(species)
    )
}

bio11 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio11) <- colnames(result$`Dulus dominicus`)
rownames(bio11) <- names(result)
bio11 <- bio11 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio12, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      ann_prec_mean = mean(species),
      ann_prec_sd = sd(species),
      ann_prec_max = max(species),
      ann_prec_min = min(species),
      ann_prec_median = median(species)
    )
}

bio12 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio12) <- colnames(result$`Dulus dominicus`)
rownames(bio12) <- names(result)
bio12 <- bio12 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio13, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      prec_wet_mean = mean(species),
      prec_wet_sd = sd(species),
      prec_wet_max = max(species),
      prec_wet_min = min(species),
      prec_wet_median = median(species)
    )
}

bio13 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio13) <- colnames(result$`Dulus dominicus`)
rownames(bio13) <- names(result)
bio13 <- bio13 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio14, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      prec_dry_mean = mean(species),
      prec_dry_sd = sd(species),
      prec_dry_max = max(species),
      prec_dry_min = min(species),
      prec_dry_median = median(species)
    )
}

bio14 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio14) <- colnames(result$`Dulus dominicus`)
rownames(bio14) <- names(result)
bio14 <- bio14 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio15, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      prec_seasonality_mean = mean(species),
      prec_seasonality_sd = sd(species),
      prec_seasonality_max = max(species),
      prec_seasonality_min = min(species),
      prec_seasonality_median = median(species)
    )
}

bio15 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio15) <- colnames(result$`Dulus dominicus`)
rownames(bio15) <- names(result)
bio15 <- bio15 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio16, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      prec_wet_quarter_mean = mean(species),
      prec_wet_quarter_sd = sd(species),
      prec_wet_quarter_max = max(species),
      prec_wet_quarter_min = min(species),
      prec_wet_quarter_median = median(species)
    )
}

bio16 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio16) <- colnames(result$`Dulus dominicus`)
rownames(bio16) <- names(result)
bio16 <- bio16 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio17, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      prec_dry_quarter_mean = mean(species),
      prec_dry_quarter_sd = sd(species),
      prec_dry_quarter_max = max(species),
      prec_dry_quarter_min = min(species),
      prec_dry_quarter_median = median(species)
    )
}

bio17 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio17) <- colnames(result$`Dulus dominicus`)
rownames(bio17) <- names(result)
bio17 <- bio17 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio18, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na()
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      prec_warm_quarter_mean = mean(species),
      prec_warm_quarter_sd = sd(species),
      prec_warm_quarter_max = max(species),
      prec_warm_quarter_min = min(species),
      prec_warm_quarter_median = median(species)
    )
}

bio18 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio18) <- colnames(result$`Dulus dominicus`)
rownames(bio18) <- names(result)
bio18 <- bio18 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(bio$bio19, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      prec_cold_quarter_mean = mean(species),
      prec_cold_quarter_sd = sd(species),
      prec_cold_quarter_max = max(species),
      prec_cold_quarter_min = min(species),
      prec_cold_quarter_median = median(species)
    )
}

bio19 <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(bio19) <- colnames(result$`Dulus dominicus`)
rownames(bio19) <- names(result)
bio19 <- bio19 %>% rownames_to_column(var = "species_name")

result = NULL
for (species in resident_npoly_complete) {
  tmp <- crop(alt, species) %>% mask(species)
  dataset <-
    as.data.frame(values(tmp)) %>% drop_na() 
  colnames(dataset) <- "species"
  result[[as.character(unique(species$SCINAME))]] <-
    dataset %>% summarise(
      prec_cold_quarter_mean = mean(species),
      prec_cold_quarter_sd = sd(species),
      prec_cold_quarter_max = max(species),
      prec_cold_quarter_min = min(species),
      prec_cold_quarter_median = median(species)
    )
}

alt <-
  data.frame(matrix(unlist(result), nrow = length(result), byrow = T))
colnames(alt) <- colnames(result$`Dulus dominicus`)
rownames(alt) <- names(result)
alt <- alt %>% rownames_to_column(var = "species_name")

total2 <-
join_all(list(bio1,bio2,bio3,bio4, bio5, bio6, bio7, bio8, bio9, bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,alt), by='species_name', type='full')

write.csv(total2, "bioclimate.csv", row.names = F)

