---
title: "0.0_regression_phyr.Rmd"
author: "Andrea Estandia<br>"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  toc: true
toc_depth: 4
editor_options:
  chunk_output_type: console
---
  <br>
  
```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/0.0_great-speciators_source.R")
```

Prepare tree for analyses
```{r}
tree_vig <- read.tree(file.path(data_path, "raw/bamm/birds_hackett.tre"))
cons_vig = ape::consensus(tree_vig, p=0.5) # To get the majority-rule consensus tree, use p = 0.5

```

Using Phyr package to do regression models while controlling for the phylogeny
```{r}
mod_mel <- pglmm(cbind(nsubsp,failures)~norm_hwi*norm_PC1+norm_precip_range*norm_altitude_range*norm_temperature_range+norm_log_max+norm_log_median+norm_netdiv+Realm+diet+habitat+migratory_status_3+(1|tree_name__), data=df_mel_final, cov_ranef = list(tree_name = mel_phylo), family="binomial", bayes = TRUE, prior="pc.prior.auto")

plot_bayes(mod_mel)

mod_mel_freq <- pglmm(cbind(nsubsp,failures)~norm_hwi*norm_PC1+norm_precip_range*norm_altitude_range*norm_temperature_range+norm_log_max+norm_log_median+norm_netdiv+Realm+diet+habitat+migratory_status_3+(1|tree_name__), data=df_mel_final, cov_ranef = list(tree_name = mel_phylo), family="binomial", bayes = FALSE)

predict <- pglmm_predicted_values(mod,
                                      type = c("link", "response")
                                      )

fitted <- fitted(mod,
                     type = c("link", "response")
                                      )
predicted_values <- cbind(predict, mod$data)

plot_habitat <- predicted_values %>%
  drop_na(
    list_vars
  ) %>%
  ggplot(aes(y = Y_hat, x = habitat)) +
  geom_jitter(col = "#886f8f", alpha = 0.4) +
  geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    color = "black"
  ) +
  theme(
    plot.title = element_text(family = "Ubuntu", size = text_size),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(
      size = text_size,
      vjust = 0.9,
      hjust = 1,
      angle = 45,
      face = "italic",
      family = "Ubuntu"
    ),
    axis.text.y = element_text(family = "Ubuntu"),
    axis.title.x = element_text(family = "Ubuntu"),
    axis.title.y = element_text(family = "Ubuntu"),
    axis.ticks.y = element_blank()
  ) + labs(y = "Number of subspecies given opportunity\n", x="\nHabitat")
 
plot_total <- plot_pc1+plot_hwi+plot_precip_range+plot_temp_range+plot_altitude+plot_max+plot_median+plot_div+plot_habitat+plot_diet+plot_realm+plot_migr

df_world_final %>%
  distinct(species_name, .keep_all = T) %>% 
  ggplot(aes(y = stdize(nsubsp/npoly,na.rm=T), x = altitude_range)) +
  geom_jitter(col = "#886f8f", alpha = 0.4)+geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    color = "black"
  )
df_world_final %>%
  distinct(species_name, .keep_all = T) %>% 
  ggplot(aes(y = norm_precip_range, x = norm_temperature_range)) +
  geom_jitter(col = "#886f8f", alpha = 0.4)+geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    color = "black"
  )

mod <- pglmm(cbind(nsubsp,failures)~norm_hwi*norm_PC1+norm_precip_range*norm_altitude_range+norm_altitude_range*norm_temperature_range+norm_temperature_range*norm_precip_range+norm_log_max+norm_log_median+norm_netdiv+Realm+diet+habitat+migratory_status_3+(1|tree_name__), data=df_world_final, cov_ranef = list(tree_name = world_phylo), family="binomial", bayes = TRUE, prior="pc.prior.auto")

null <- pglmm(cbind(nsubsp,failures)~1+(1|tree_name__), data=df_world_final, cov_ranef = list(tree_name = world_phylo), family="binomial", bayes = TRUE, prior="pc.prior.auto")

deviance <- 2*(mod$logLik - null$logLik)
pchisq(deviance, df=1, lower.tail=F)
LRT.b1 <- c(dev = deviance, p.value=pchisq(deviance, df=1, lower.tail=F))

test_nested <- phyr::pglmm_profile_LRT(mod, re.number = 6)
LRTs <- sapply(1:6, FUN = function(x) 
  phyr::pglmm_profile_LRT(mod, re.number = x))
colnames(LRTs) <- names(mod$ss)
t(LRTs)

plot_bayes(mod, predicted = TRUE)
rr2::R2(mod)

mod_freq <- pglmm(cbind(nsubsp,failures)~hwi*PC1+precip_range*altitude_range+altitude_range*temperature_range+temperature_range*precip_range+log_max+log_median+netdiv+Realm+latitude+diet+habitat+migratory_status_3+(1|tree_name__), data=g2, cov_ranef = list(tree_name = vig_phylo), family="binomial", bayes = FALSE, prior="pc.prior.auto")
```

