---
title: "0.0_simulation.Rmd"
author: "Andrea Estandia<br>"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  toc: true
toc_depth: 4
editor_options:
  chunk_output_type: console
---
  <br>
  
```{r setup, echo=FALSE}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r, echo=FALSE}
source("./src/0.0_great-speciators_source.R")
```

```{r}
library(rcoalescence)
input_dir <- file.path(data_path, "simulation")
output_dir <- file.path(output_path, "simulation")
figures_directory <- file.path(output_path, "simulation/figs")

if (!dir.exists(input_dir)) {
  dir.create(input_dir)
}

if (!dir.exists(output_dir)) {
  dir.create(output_dir)
}

if (!dir.exists(figures_directory)) {
  dir.create(figures_directory)
}
```

```{r}
islands_list <- paste0("V", seq(1:73))

land <-
  sf::st_read(dsn = file.path(data_path, "shapefiles/melanesia.shp")) %>%
  mutate(area = st_area(.) / 1000000) %>% drop_units() %>% filter(area < 587000)

island_dispersal <- land %>% 
  st_cast("MULTIPOLYGON") %>%  
  st_cast("POLYGON", warn=F) %>% 
  st_centroid() %>% 
  st_distance() %>% 
  as_tibble() %>% 
  drop_units()

island_dispersal <-
  island_dispersal/rowSums(island_dispersal) 
  #mutate("island" = islands_list)

island_dispersal <- as.matrix(island_dispersal)

writeTIFF(island_dispersal, "island.tif")

#names(island_dispersal) <- c(islands_list, "island")

coordinates <- land %>% st_cast("MULTIPOLYGON") %>%  
  st_cast("POLYGON", warn=F) %>% 
  st_centroid() %>% 
  st_coordinates() %>% 
  as_tibble
```

```{r}
density_island <- vector(length=73) %>% replace_na(0) %>% as.matrix()
density_island[1] <- 100

x <- rnorm(25, mean = 100, sd = 15) 
density_island <-  as.matrix(pnorm(x, mean = 100, sd = 15))

density_island <- rbinom(73, size = 100, prob = 0.5)

writeTIFF(density_island, "density_island.tif")

known_species_richness <- 1
```

```{r}
density_file <- readTIFF(file.path(input_dir, "density_island.tif"))
dispersal_file <- readTIFF(file.path(input_dir, "island.tif"))

island_coordinates <- data.frame(
  island =  paste0("V", seq(1:73)),
  x = coordinates$X,
  y = coordinates$Y,
  x_old =  seq(1:73)
)

island_density_df <- t(t(density_file)) %>%
  as_tibble() %>%
  mutate("island" = islands_list) %>%
  rename(no_individuals = V1) %>%
  dplyr::select(island, no_individuals)

dispersal_probabilities <- island_dispersal %>%
  pivot_longer(
    names_to = "destination",
    values_to = "probability",
    cols =paste0("V", seq(1:73))
  ) %>% 
  rename(source = island) %>%
  full_join(island_coordinates, by = c(source = "island")) %>%
  rename(x_source = x, y_source = y) %>%
  full_join(island_coordinates, by = c(destination = "island")) %>%
  rename(x_destination = x, y_destination = y) %>%
  filter(!(x_source == x_destination & y_source == y_destination)) 
  

```



```{r}
sdplants=0
nm.setup <- function(gridlength, nplants, spinit)
{
  habdata <- data.frame(matrix(nrow = gridlength ^ 2, ncol = 5))
  names(habdata) <- c("cell", "xpos", "ypos", "species", "nsubsp")
  habdata$cell <- as.integer(1:gridlength ^ 2)
  habdata$xpos <- (habdata$cell - 1) %% gridlength + 1
  habdata$ypos <- (habdata$cell - 1) %/% gridlength + 1
  relabund <- rlnorm(n = nplants,
                     meanlog = 0,
                     sdlog = sdplants)
  if (length(relabund) != nplants)
    browser()
  habdata$plant <- as.integer(sample(
    x = 1:nplants,
    size = gridlength ^ 2,
    replace = TRUE,
    prob = relabund
  ))
  occ.cells <- as.integer(sample(
    x = 1:(gridlength ^ 2),
    size = spinit,
    replace = FALSE
  ))
  habdata$nsubsp <- replace(x = habdata$nsubsp,
                            list = occ.cells,
                            values = 1:spinit)
  habdata
}

nm.setup(gridlength = 5, nplants = 10, spinit = 1)
```